import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const AccountantMenuStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
    mainHeader: {
        backgroundColor: COLORS.headerBg,
        paddingTop: 60,
        paddingHorizontal: 20,
        paddingBottom: 70,
        position: 'relative',
        overflow: 'hidden',
        zIndex: 1,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -50,
        right: -50,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(255,255,255,0.06)',
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerSubTitle: {
        color: COLORS.secondary,
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
        marginBottom: 4,
    },
    headerTitle: { color: COLORS.white, fontSize: 24, fontWeight: '800' },
    profileAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: 'rgba(76, 175, 80, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(76, 175, 80, 0.5)',
    },
    avatarText: { color: COLORS.secondary, fontSize: 20, fontWeight: '800' },

    scrollView: { flex: 1, marginTop: -40 },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },

    statsFloatingCard: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 25,
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 15,
        shadowOffset: { width: 0, height: 4 },
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
    },
    divider: { width: 1, backgroundColor: COLORS.inputBg, marginHorizontal: 15 },
    statBox: { flex: 1, alignItems: 'center' },
    statIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    statLabel: {
        color: COLORS.textMuted,
        fontSize: 11,
        fontWeight: '800',
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    statValue: { fontSize: 26, fontWeight: '800' },
    statUnit: { color: COLORS.textGray, fontSize: 12, marginTop: 2, fontWeight: '600' },

    sectionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: COLORS.primary,
        letterSpacing: 1,
        marginBottom: 15,
    },
    grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    mainCard: {
        width: '48%',
        backgroundColor: COLORS.white,
        borderRadius: 20,
        padding: 18,
        marginBottom: 15,
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        borderWidth: 1,
        borderColor: COLORS.inputBg,
    },
    mainCardIconWrap: {
        width: 50,
        height: 50,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
    },
    mainCardTitle: { fontSize: 15, fontWeight: '800', color: COLORS.primary, marginBottom: 6 },
    mainCardSub: { fontSize: 12, color: COLORS.textMuted, lineHeight: 18, fontWeight: '500' },
});

export default AccountantMenuStyles;
