import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    backgroundColor: PRIMARY,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    zIndex: 10,
  },
  headerCenter: { flex: 1, alignItems: "center", paddingHorizontal: 12 },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  headerSub: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
    textAlign: "center",
  },

  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  headerButtonInner: { justifyContent: "center", alignItems: "center" },

  tabRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "#F1F5F9",
  },
  tabButtonActive: { backgroundColor: PRIMARY },
  tabText: {
    textAlign: "center",
    color: "#64748B",
    fontWeight: "800",
    fontSize: 12,
  },
  tabTextActive: { color: "#FFFFFF" },

  // Card Phẳng Chuẩn DNA
  summaryCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryLabel: { fontSize: 12, color: "#64748B", fontWeight: "700" },
  summaryValue: {
    fontSize: 28,
    color: PRIMARY,
    fontWeight: "900",
    marginTop: 2,
  },
  summaryHint: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
    marginTop: 6,
  },

  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },

  // Empty State Chuẩn
  emptyIconBox: {
    width: 66,
    height: 66,
    borderRadius: 22,
    backgroundColor: "rgba(245, 249, 255, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  emptyText: {
    textAlign: "center",
    color: "#64748B",
    fontWeight: "700",
    fontSize: 14,
  },

  listContent: { padding: 16, paddingBottom: 120 },

  card: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    marginBottom: 16,
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardChecked: { borderColor: PRIMARY, backgroundColor: "#F0FDF4" },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 10,
  },
  cardTitleWrap: { flex: 1, flexDirection: "row", alignItems: "flex-start" },
  requestCode: { fontSize: 15, fontWeight: "900", color: "#0F172A" },
  subCode: { fontSize: 12, color: "#64748B", marginTop: 4, fontWeight: "700" },

  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  statusText: { fontSize: 10, fontWeight: "900" },
  sourcePill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  sourcePillText: { fontSize: 10, fontWeight: "800" },

  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 12,
  },
  metaLabel: { fontSize: 13, color: "#64748B", fontWeight: "600", flex: 1 },
  metaValue: {
    fontSize: 13,
    color: "#0F172A",
    fontWeight: "700",
    flex: 1.2,
    textAlign: "right",
  },

  actionRow: { flexDirection: "row", marginTop: 16, gap: 12 },
  secondaryAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  secondaryActionText: { color: "#64748B", fontWeight: "800" },
  primaryActionWrap: {
    flex: 1.5,
    borderRadius: 12,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
  },
  rejectActionWrap: {
    flex: 1.5,
    borderRadius: 12,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
  },
  primaryActionText: { color: "#FFFFFF", fontWeight: "900" },

  uploadActions: { flexDirection: "row", gap: 12, marginBottom: 16 },

  // Bottom Bar Chuẩn Form
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  dispatchButton: {
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
  },
  dispatchButtonText: { color: "#FFFFFF", fontWeight: "900", fontSize: 15 },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    maxHeight: "70%",
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 16,
  },

  modalItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  modalItemTitle: { fontSize: 15, color: "#0F172A", fontWeight: "800" },
  modalItemSub: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "700",
    marginTop: 4,
  },
  emptyModalText: {
    color: "#64748B",
    fontWeight: "700",
    textAlign: "center",
    marginVertical: 20,
  },

  noteInput: {
    minHeight: 110,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: "top",
    color: "#0F172A",
    marginBottom: 16,
    fontWeight: "600",
  },
});
