import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";
const WHITE = COLORS.white || "#FFFFFF";
const SURFACE = COLORS.surface || "#FFFFFF";
const SURFACE_SOFT = COLORS.surfaceSoft || "#F8FAFC";
const SURFACE_MUTED = COLORS.surfaceMuted || "#F1F5F9";

const shadow = {
  ...Platform.select({
    ios: {
      shadowColor: COLORS.primaryDark || PRIMARY,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
    },
    android: {
      elevation: 2,
    },
  }),
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC'},
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 52 : 38,
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    overflow: "hidden",
  },
  headerOrbOne: {
    position: "absolute",
    top: -80,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  headerOrbTwo: {
    position: "absolute",
    left: -35,
    bottom: -70,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  headerLine: {
    position: "absolute",
    top: Platform.OS === "ios" ? 48 : 32,
    left: 24,
    right: 24,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.36)",
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  headerCenter: { flex: 1, alignItems: "center", paddingHorizontal: 12 },
  headerTitle: { color: WHITE, fontSize: 18, fontWeight: "900" },
  headerSub: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "center",
  },
  tabRow: { flexDirection: "row", paddingHorizontal: 16, marginTop: 14, marginBottom: 10 },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 18,
    marginRight: 8,
    backgroundColor: COLORS.borderSoft,
  },
  tabButtonActive: { backgroundColor: PRIMARY },
  tabText: { textAlign: "center", color: COLORS.textSecondary, fontWeight: "800", fontSize: 13 },
  tabTextActive: { color: WHITE },
  summaryCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    ...shadow,
  },
  summaryLabel: { fontSize: 12, color: COLORS.textSecondary, fontWeight: "700" },
  summaryValue: { fontSize: 28, color: PRIMARY, fontWeight: "900", marginTop: 2 },
  summaryHint: { fontSize: 12, color: COLORS.textSecondary, fontWeight: "700", marginTop: 6 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 24 },
  emptyIconBox: {
    width: 74,
    height: 74,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  emptyText: { textAlign: "center", color: COLORS.textSecondary, fontWeight: "800" },
  listContent: { padding: 16, paddingBottom: 120 },
  cardShadow: { borderRadius: 16, marginBottom: 14, ...shadow },
  card: {
    borderRadius: 16,
    padding: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.84)",
  },
  cardChecked: { borderColor: "rgba(15,61,38,0.32)" },
  cardTopLine: {
    position: "absolute",
    top: 1,
    left: 18,
    right: 18,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.96)",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 10,
  },
  cardTitleWrap: { flex: 1, flexDirection: "row", alignItems: "flex-start" },
  requestCode: { fontSize: 16, fontWeight: "900", color: COLORS.textPrimary },
  subCode: { fontSize: 12, color: COLORS.textSecondary, marginTop: 4, fontWeight: "700" },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  statusText: { fontSize: 11, fontWeight: "900" },
  metaRow: { marginTop: 8 },
  metaLabel: { fontSize: 12, color: COLORS.textSecondary, fontWeight: "700", marginBottom: 2 },
  metaValue: { fontSize: 14, color: COLORS.textPrimary, fontWeight: "700", lineHeight: 20 },
  actionRow: { flexDirection: "row", marginTop: 14 },
  secondaryAction: {
    flex: 1,
    minHeight: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: COLORS.borderMuted,
    marginRight: 10,
  },
  secondaryActionText: { color: COLORS.textSecondary, fontWeight: "900" },
  primaryActionWrap: { flex: 1.2, borderRadius: 16, overflow: "hidden" },
  primaryAction: {
    minHeight: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionText: { color: WHITE, fontWeight: "900" },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 14,
    paddingBottom: Platform.OS === "ios" ? 24 : 18,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.88)",
    backgroundColor: "rgba(255,255,255,0.84)",
  },
  dispatchButtonWrap: { borderRadius: 18, overflow: "hidden" },
  dispatchButton: {
    minHeight: 50,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  dispatchButtonText: { color: WHITE, fontWeight: "900", fontSize: 15 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    maxHeight: "70%",
    borderRadius: 16,
    backgroundColor: SURFACE,
    padding: 16,
  },
  rejectCard: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    padding: 16,
  },
  modalTitle: { fontSize: 18, fontWeight: "900", color: COLORS.textPrimary, marginBottom: 14 },
  modalItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderSoft,
  },
  modalItemTitle: { fontSize: 15, color: COLORS.textPrimary, fontWeight: "800" },
  modalItemSub: { fontSize: 12, color: COLORS.textSecondary, fontWeight: "700", marginTop: 4 },
  emptyModalText: { color: COLORS.textSecondary, fontWeight: "700" },
  noteInput: {
    minHeight: 110,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.borderMuted,
    backgroundColor: SURFACE_SOFT,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: "top",
    color: COLORS.textPrimary,
    marginBottom: 14,
  },
});
