import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const CashConfirmStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.backgroundSoft,
    },
    headerArea: {
        backgroundColor: COLORS.headerBg,
        paddingTop: Platform.OS === 'ios' ? 52 : 34,
        paddingBottom: 48,
        paddingHorizontal: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'relative',
        overflow: 'hidden',
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -30,
        right: -40,
        width: 160,
        height: 160,
        borderRadius: 80,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.14)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: 'bold',
    },
    listContainer: {
        flex: 1,
        marginTop: -28,
    },
    listContent: {
        paddingHorizontal: 20,
        paddingBottom: 30,
    },
    emptyContainer: {
        backgroundColor: COLORS.white,
        borderRadius: 18,
        paddingHorizontal: 25,
        paddingVertical: 40,
        marginTop: 30,
        alignItems: 'center',
    },
    emptyText: {
        marginTop: 14,
        color: '#66726a',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
    },
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 18,
        padding: 18,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#edf1ed',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: 14,
        marginBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#edf1ed',
    },
    cardHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e8f5e9',
    },
    shipperName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.primary,
        marginLeft: 12,
        flexShrink: 1,
    },
    badgeCount: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#edf8ef',
    },
    badgeText: {
        color: COLORS.secondary,
        fontSize: 12,
        fontWeight: 'bold',
    },
    cardBody: {
        alignItems: 'center',
        marginBottom: 18,
    },
    label: {
        color: '#738078',
        fontSize: 13,
        fontWeight: '500',
    },
    codAmountRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: 6,
    },
    codAmount: {
        fontSize: 34,
        fontWeight: 'bold',
        color: COLORS.error,
    },
    codCurrency: {
        marginTop: 4,
        marginLeft: 4,
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.error,
    },
    confirmBtn: {
        height: 50,
        borderRadius: 14,
        backgroundColor: COLORS.secondary,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmBtnDisabled: {
        opacity: 0.7,
    },
    btnText: {
        color: COLORS.white,
        fontSize: 15,
        fontWeight: 'bold',
        marginLeft: 8,
    },
});

export default CashConfirmStyles;
