import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";
const WHITE = COLORS.white || "#FFFFFF";
const SURFACE = COLORS.surface || "#FFFFFF";
const SURFACE_SOFT = COLORS.surfaceSoft || "#F8FAFC";
const SURFACE_MUTED = COLORS.surfaceMuted || "#F1F5F9";
const TEXT_PRIMARY = COLORS.textPrimary || "#0F172A";
const TEXT_SECONDARY = COLORS.textSecondary || "#475569";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC'},
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    backgroundColor: PRIMARY,
    ...Platform.select({
      ios: { shadowColor: PRIMARY, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
  },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: "center",
    alignItems: "center",
  },
  headerButtonInner: { justifyContent: "center", alignItems: "center" },
  headerCenter: { alignItems: "center", flex: 1, paddingHorizontal: 10 },
  headerTitle: { color: "white", fontSize: 18, fontWeight: "900" },
  headerSubtitle: { color: "rgba(255,255,255,0.85)", fontSize: 12, marginTop: 2, fontWeight: "700" },
  draftPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  draftText: { color: "white", fontSize: 13, fontWeight: "800" },
  scrollContent: { padding: 16, paddingBottom: 140 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: COLORS.primary,
    marginBottom: 12,
    marginTop: 20,
    marginLeft: 4,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: TEXT_SECONDARY,
    marginBottom: 8,
  },
  card: {
    backgroundColor: SURFACE,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    marginBottom: 10,
    ...Platform.select({
      ios: { shadowColor: "#64748B", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
  },
  input: {
    backgroundColor: SURFACE_SOFT,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 52,
    fontSize: 15,
    color: TEXT_PRIMARY,
    fontWeight: "600",
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    marginBottom: 16,
  },
  selectionBox: {
    backgroundColor: SURFACE_SOFT,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 52,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    marginBottom: 16,
  },
  selectionText: { color: TEXT_PRIMARY, fontSize: 15, fontWeight: "600" },
  dropdownContainer: {
    position: "absolute",
    top: 56,
    left: 0,
    right: 0,
    backgroundColor: SURFACE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    ...Platform.select({
      ios: { shadowColor: "#64748B", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
    zIndex: 100,
  },
  dropdownItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: SURFACE_MUTED,
  },
  dropdownItemText: { fontSize: 15, color: TEXT_PRIMARY, fontWeight: "600" },
  rowInputs: { flexDirection: "row", justifyContent: "space-between" },
  flexInput: { flex: 1 },
  spacedInput: { marginRight: 12 },
  radioGroup: {
    flexDirection: "row",
    marginBottom: 16,
    backgroundColor: SURFACE_MUTED,
    borderRadius: 12,
    padding: 4,
  },
  radioBtn: { flex: 1, paddingVertical: 12, alignItems: "center", borderRadius: 10 },
  radioBtnActive: {
    backgroundColor: SURFACE,
    ...Platform.select({
      ios: { shadowColor: "#64748B", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
  },
  radioText: { color: COLORS.textSecondary || "#64748B", fontSize: 14, fontWeight: "700" },
  radioTextActive: { color: PRIMARY, fontWeight: "900" },
  checkboxRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  checkboxLabel: {
    marginLeft: 10,
    fontSize: 14,
    color: TEXT_PRIMARY,
    fontWeight: "600",
  },
  billingRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  billingLabel: { color: COLORS.textSecondary || "#64748B", fontSize: 14, fontWeight: "700" },
  billingValue: { color: TEXT_PRIMARY, fontSize: 14, fontWeight: "700" },
  bottomDock: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: SURFACE,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderSoft || "#E2E8F0",
    ...Platform.select({
      ios: { shadowColor: "#64748B", shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
  },
  confirmBtn: {
    backgroundColor: COLORS.primary,
    minHeight: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBtnText: { color: WHITE, fontSize: 16, fontWeight: "900" },
  textArea: {
    minHeight: 86,
    paddingTop: 14,
    textAlignVertical: "top",
  },
  selectionBoxDisabled: { opacity: 0.5 },
  addressPreview: {
    borderRadius: 12,
    backgroundColor: SURFACE_SOFT,
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    padding: 14,
  },
  addressPreviewLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textSecondary || "#64748B",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  addressPreviewValue: { color: TEXT_PRIMARY, fontSize: 13, fontWeight: "600" },
  segmentRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    backgroundColor: SURFACE_SOFT,
    paddingVertical: 12,
    alignItems: "center",
  },
  segmentButtonActive: {
    backgroundColor: `${PRIMARY}12`,
    borderColor: `${PRIMARY}44`,
  },
  segmentText: { color: TEXT_SECONDARY, fontSize: 14, fontWeight: "800" },
  segmentTextActive: { color: PRIMARY },
  rowHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 10,
  },
  helperText: {
    flex: 1,
    color: COLORS.textSecondary || "#64748B",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
  },
  smallButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: `${PRIMARY}33`,
  },
  smallButtonText: { color: PRIMARY, fontSize: 12, fontWeight: "800" },
  draftRow: {
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#FCFDFE",
  },
  draftRowHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  draftRowTitle: { color: TEXT_PRIMARY, fontSize: 14, fontWeight: "900" },
  primaryBtn: {
    flex: 1.4,
    backgroundColor: PRIMARY,
    height: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: WHITE, fontSize: 15, fontWeight: "900" },
  secondaryBtn: {
    flex: 1,
    backgroundColor: SURFACE_MUTED,
    height: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.borderSoft || "#E2E8F0",
  },
  secondaryBtnText: { color: TEXT_SECONDARY, fontSize: 14, fontWeight: "800" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: SURFACE,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "75%",
    padding: 20,
    ...Platform.select({
      ios: { shadowColor: "#000", shadowOffset: { width: 0, height: -10 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 2 },
    }),
  },
  modalHandle: {
    width: 42,
    height: 5,
    backgroundColor: COLORS.borderSoft || "#E2E8F0",
    borderRadius: 999,
    alignSelf: "center",
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: SURFACE_MUTED,
    marginBottom: 12,
  },
  modalTitle: { fontSize: 18, fontWeight: "900", color: TEXT_PRIMARY },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: SURFACE_MUTED,
  },
  modalItemText: { fontSize: 16, color: TEXT_PRIMARY, fontWeight: "600" },
});
