import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "white" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 25,
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    backgroundColor: COLORS.primary || "#1B5E20",
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    zIndex: 10,
  },
  headerTextGroup: { flex: 1 },
  greeting: {
    fontSize: Platform.OS === "ios" ? 14 : 11,
    color: "rgba(255,255,255,0.7)",
    letterSpacing: 0.5,
  },
  userName: {
    fontSize: Platform.OS === "ios" ? 18 : 12,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 4,
    marginBottom: 8,
  },
  roleBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  roleDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
  roleText: {
    fontSize: Platform.OS === "ios" ? 13 : 10,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  appleCircleBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  appleBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#EF4444",
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.primary || "#1B5E20",
    paddingHorizontal: 4,
  },
  appleBadgeText: { color: "#FFF", fontSize: 10, fontWeight: "800" },
  menuOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.1)' },
  dropdownMenu: {
    position: "absolute",
    top: Platform.OS === "ios" ? 115 : 75,
    right: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    width: 220,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  menuIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  menuText: { flex: 1, fontSize: 14, fontWeight: "600", color: "#374151" },
  menuDivider: { height: 1, backgroundColor: "#F3F4F6", marginHorizontal: 16 },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 20 },
  listContainer: { paddingBottom: 40 },
  rowWrapper: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  gridCard: {
    backgroundColor: "#FFFFFF",
    width: "48%",
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 16,
  },
  cardBadgeText: {
    fontSize: Platform.OS === "ios" ? 10 : 6,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  gridIconBox: {
    width: 52,
    height: 52,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    marginTop: 8,
  },
  gridCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    textAlign: "center",
    marginBottom: 4,
    lineHeight: 20,
    minHeight: 36,
  },
  gridCardDesc: {
    fontSize: Platform.OS === "ios" ? 12 : 9,
    color: "#94A3B8",
    textAlign: "center",
  },
  emptyState: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    paddingVertical: 30,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 16,
    backgroundColor: "#FFF",
  },
  emptyIconBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#374151",
    marginBottom: 8,
  },
  emptyText: {
    textAlign: "center",
    color: "#6B7280",
    paddingHorizontal: 30,
    lineHeight: 20,
  },
});
