import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    backgroundColor: PRIMARY,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    zIndex: 10,
  },
  headerCenter: { alignItems: "center", flex: 1 },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerButtonInner: { justifyContent: "center", alignItems: "center" },
  searchSection: {
    margin: 16,
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    paddingHorizontal: 12,
    minHeight: 52,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 15, color: "#0F172A", fontWeight: "700" },
  searchBtn: {
    backgroundColor: PRIMARY,
    height: 48,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBtnText: { color: "white", fontSize: 15, fontWeight: "900" },
  centerContent: { flex: 1, justifyContent: "center", alignItems: "center" },
  centerContentInline: {
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  emptyIconBox: {
    width: 66,
    height: 66,
    borderRadius: 22,
    backgroundColor: "rgba(241,245,249,0.8)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  placeholderText: { color: "#0F172A", fontSize: 15, fontWeight: "800" },
  emptyText: { color: "#64748B", fontSize: 14, fontWeight: "600" },
  resultContainer: { padding: 16, paddingBottom: 50 },
  card: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    paddingBottom: 8,
  },
  timelineTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#0F172A",
    marginLeft: 4,
    marginTop: 4,
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  label: { color: "#64748B", fontSize: 14, flex: 1, fontWeight: "600" },
  value: {
    color: "#0F172A",
    fontSize: 14,
    flex: 1,
    textAlign: "right",
    fontWeight: "700",
  },
  valueBold: {
    color: PRIMARY,
    fontSize: 14,
    fontWeight: "900",
    flex: 1,
    textAlign: "right",
  },
  timelineItem: { flexDirection: "row" },
  timelineColumn: { width: 20, alignItems: "center", marginRight: 15 },
  dot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#CBD5E1",
    zIndex: 2,
    marginTop: 4,
  },
  activeDot: { backgroundColor: PRIMARY },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: -4,
    zIndex: 1,
  },
  contentColumn: { flex: 1, paddingBottom: 25 },
  logStatus: { fontSize: 15, fontWeight: "800", color: "#0F172A" },
  logTime: { fontSize: 13, color: "#64748B", marginTop: 4, fontWeight: "600" },
  logLocation: {
    fontSize: 13,
    color: "#475569",
    marginTop: 4,
    fontWeight: "600",
  },
  logNote: {
    fontSize: 13,
    color: "#EF4444",
    marginTop: 4,
    fontStyle: "italic",
    fontWeight: "700",
  },
});
