import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";
const WHITE = COLORS.white || "#FFFFFF";
const SURFACE_MUTED = COLORS.surfaceMuted || "#F1F5F9";

const glassShadow = {
  ...Platform.select({
    ios: {
      shadowColor: COLORS.primaryDark || PRIMARY,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.13,
      shadowRadius: 22,
    },
    android: {
      elevation: 5,
    },
  }),
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: SURFACE_MUTED },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 25,
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    backgroundColor: PRIMARY,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    overflow: "hidden",
    zIndex: 10,
    ...Platform.select({
      ios: {
        shadowColor: PRIMARY,
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.22,
        shadowRadius: 18,
      },
      android: { elevation: 8 },
    }),
  },
  headerOrbOne: {
    position: "absolute",
    width: 190,
    height: 190,
    borderRadius: 95,
    top: -80,
    right: -62,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  headerOrbTwo: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    bottom: -70,
    left: -42,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  headerGlassLine: {
    position: "absolute",
    left: 28,
    right: 28,
    top: Platform.OS === "ios" ? 48 : 28,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  headerTextGroup: { flex: 1, paddingRight: 12 },
  greeting: {
    fontSize: Platform.OS === "ios" ? 14 : 11,
    color: "rgba(255,255,255,0.78)",
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  userName: {
    fontSize: Platform.OS === "ios" ? 20 : 14,
    fontWeight: "900",
    color: WHITE,
    marginTop: 4,
    marginBottom: 8,
  },
  roleBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  roleDot: { width: 7, height: 7, borderRadius: 4, marginRight: 7 },
  roleText: {
    fontSize: Platform.OS === "ios" ? 13 : 10,
    color: WHITE,
    fontWeight: "700",
  },
  headerActions: { flexDirection: "row", alignItems: "center" },
  headerButtonShadow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.14,
        shadowRadius: 10,
      },
      android: { elevation: 4 },
    }),
  },
  appleCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  appleCircleBtnDanger: { backgroundColor: "rgba(239,68,68,0.78)", borderColor: "rgba(255,255,255,0.36)" },
  headerButtonTopLine: {
    position: "absolute",
    top: 1,
    left: 8,
    right: 8,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 20 },
  quickActions: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 },
  actionCardShadow: { width: "48%", borderRadius: 24, ...glassShadow },
  actionCardShadowWide: { width: "100%", marginTop: 12 },
  actionCard: {
    minHeight: 150,
    padding: 15,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.86)",
    alignItems: "center",
    backgroundColor: Platform.OS === "android" ? "rgba(255,255,255,0.82)" : "rgba(255,255,255,0.36)",
  },
  actionCardWide: { width: "100%" },
  actionCardHorizontal: { minHeight: 92, flexDirection: "row", alignItems: "center", padding: 20 },
  cardTopLine: {
    position: "absolute",
    top: 1,
    left: 18,
    right: 18,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.96)",
  },
  cardGlow: {
    position: "absolute",
    top: 12,
    left: 14,
    width: 58,
    height: 28,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.28)",
    transform: [{ rotate: "-18deg" }],
  },
  iconBox: {
    width: 62,
    height: 62,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    overflow: "hidden",
  },
  iconBoxHorizontal: { marginBottom: 0, marginRight: 15 },
  horizontalTextGroup: { flex: 1 },
  actionTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: COLORS.textPrimary,
    marginBottom: 4,
    textAlign: "center",
  },
  actionTitleWide: { fontSize: 16, textAlign: "left" },
  actionDesc: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
    fontWeight: "600",
    lineHeight: 17,
  },
  actionDescLeft: { textAlign: "left", fontSize: 13 },
  sectionBlock: { marginTop: 20 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  emptyStateShadow: { borderRadius: 24, ...glassShadow },
  emptyState: {
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.86)",
    backgroundColor: Platform.OS === "android" ? "rgba(255,255,255,0.82)" : "rgba(255,255,255,0.36)",
  },
  emptyIconBg: {
    width: 66,
    height: 66,
    borderRadius: 24,
    backgroundColor: "rgba(243,244,246,0.82)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.86)",
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  emptyText: {
    textAlign: "center",
    color: COLORS.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  headerButtonDanger: { backgroundColor: "rgba(239,68,68,0.78)" },
  headerButtonInner: {
    position: "absolute",
    top: 1,
    left: 8,
    right: 8,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
});
