import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

const glassShadow = {
  ...Platform.select({
    ios: {
      shadowColor: "#123816",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.13,
      shadowRadius: 22,
    },
    android: { elevation: 5 },
  }),
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.surfaceMuted || "#F1F5F9" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 52 : 40,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: PRIMARY,
    overflow: "hidden",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerOrbOne: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    top: -70,
    right: -45,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  headerOrbTwo: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    bottom: -70,
    left: -38,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  headerGlassLine: {
    position: "absolute",
    top: Platform.OS === "ios" ? 48 : 32,
    left: 24,
    right: 24,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  headerButtonShadow: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  headerButton: {
    flex: 1,
    borderRadius: 21,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  headerButtonTopLine: {
    position: "absolute",
    top: 1,
    left: 9,
    right: 9,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  headerCenter: { alignItems: "center", flex: 1, paddingHorizontal: 10 },
  headerTitle: { color: "white", fontSize: 18, fontWeight: "900" },
  headerSub: { color: "rgba(255,255,255,0.85)", fontSize: 12, marginTop: 2, fontWeight: "700" },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyIconBox: {
    width: 76,
    height: 76,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.82)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
  },
  emptyText: { color: COLORS.textSecondary, fontSize: 15, fontWeight: "700" },
  listContent: { padding: 15, paddingBottom: 130 },
  cardShadow: { borderRadius: 24, marginBottom: 12, ...glassShadow },
  card: {
    borderRadius: 24,
    padding: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.86)",
    backgroundColor: Platform.OS === "android" ? "rgba(255,255,255,0.84)" : "rgba(255,255,255,0.36)",
  },
  cardChecked: { borderColor: "rgba(27,94,32,0.38)" },
  cardTopLine: {
    position: "absolute",
    top: 1,
    left: 18,
    right: 18,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.96)",
  },
  cardGlow: {
    position: "absolute",
    top: 12,
    left: 14,
    width: 62,
    height: 30,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.26)",
    transform: [{ rotate: "-18deg" }],
  },
  cardHeader: { flexDirection: "row", alignItems: "flex-start", marginBottom: 8 },
  checkBox: { marginTop: 2, marginRight: 10 },
  title: { fontSize: 15, fontWeight: "900", color: COLORS.textPrimary },
  subText: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2, fontWeight: "700" },
  deleteBtn: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },
  meta: { fontSize: 12, color: COLORS.textSecondary, marginTop: 4, fontWeight: "700" },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    padding: 14,
    paddingBottom: Platform.OS === "ios" ? 24 : 18,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.86)",
    overflow: "hidden",
  },
  secondaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "rgba(27,94,32,0.22)",
    marginRight: 10,
  },
  secondaryBtnText: { color: PRIMARY, fontWeight: "900" },
  primaryBtn: { flex: 1.2, borderRadius: 18, overflow: "hidden" },
  primaryBtnGradient: { minHeight: 48, borderRadius: 18, alignItems: "center", justifyContent: "center" },
  primaryBtnText: { color: "white", fontWeight: "900" },
});
