import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0F2F5",
  },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 55 : 44,
    paddingBottom: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  headerTextGroup: {
    flex: 1,
  },
  greeting: {
    fontSize: 12,
    color: "rgba(255,255,255,0.65)",
    marginBottom: 3,
  },
  userName: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -0.3,
  },
  rolePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    marginTop: 8,
  },
  roleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 5,
  },
  roleText: {
    fontSize: 11,
    color: "#fff",
    fontWeight: "600",
  },
  headerBtns: {
    flexDirection: "row",
    gap: 8,
  },
  headerBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
  },
  notifWrap: {
    position: "relative",
  },
  notifDot: {
    position: "absolute",
    top: -3,
    right: -3,
    width: 10,
    height: 10,
    backgroundColor: "#EF4444",
    borderRadius: 5,
    borderWidth: 2,
    borderColor: PRIMARY,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  scrollContent: {
    paddingTop: 14,
    paddingBottom: 40,
  },
  bannerWrap: {
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  banner: {
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: "#E8EDF2",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  bannerIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  bannerTextGroup: {
    flex: 1,
  },
  bannerTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 3,
  },
  bannerSub: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: "600",
  },
  bannerArrow: {
    marginLeft: "auto",
  },
  sec: {
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  secHdr: {
    marginBottom: 10,
  },
  secTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gcard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: "#E8EDF2",
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 10,
    position: "relative",
    overflow: "hidden",
  },
  gcardBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 8,
  },
  gcardBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  gcardIco: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 4,
  },
  gcardTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
    lineHeight: 18,
    marginBottom: 3,
  },
  gcardDesc: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "600",
  },
  empty: {
    marginHorizontal: 12,
    marginBottom: 12,
    borderWidth: 0.5,
    borderColor: "#E8EDF2",
    borderRadius: 14,
    backgroundColor: "#fff",
    padding: 20,
    alignItems: "center",
  },
  emptyIco: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  emptyT: {
    fontSize: 13,
    fontWeight: "800",
    color: "#374151",
    marginBottom: 4,
  },
  emptyS: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 16,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  dropdownMenu: {
    position: "absolute",
    top: Platform.OS === "ios" ? 100 : 80,
    right: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    width: 220,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  menuIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  menuText: { flex: 1, fontSize: 14, fontWeight: "600", color: "#374151" },
  menuDivider: { height: 1, backgroundColor: "#F3F4F6", marginHorizontal: 16 },
});
