import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  keyboardRoot: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    backgroundColor: PRIMARY,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    zIndex: 10,
  },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  headerButtonInner: { justifyContent: "center", alignItems: "center" },
  content: { flex: 1, padding: 20, justifyContent: "center" },
  formCard: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  stepIconBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "#F8FAFC",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  instruction: {
    fontSize: 14,
    color: "#475569",
    marginBottom: 20,
    lineHeight: 21,
    textAlign: "center",
    fontWeight: "600",
  },
  instructionBold: { fontWeight: "900", color: "#0F172A" },
  label: { fontSize: 13, color: "#475569", marginBottom: 8, fontWeight: "700" },
  inputGroup: { marginBottom: 16 },
  inputWrapper: {
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
  },
  inputIcon: { marginLeft: 14, marginRight: 8 },
  input: {
    flex: 1,
    minHeight: 52,
    paddingVertical: 0,
    fontSize: 15,
    color: "#0F172A",
    fontWeight: "600",
  },
  eyeIcon: {
    width: 46,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  saveBtn: {
    borderRadius: 12,
    marginTop: 10,
    minHeight: 52,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: { color: "#FFF", fontSize: 16, fontWeight: "900" },
  resendBtn: { alignItems: "center", marginTop: 20 },
  resendText: { color: PRIMARY, fontWeight: "800", fontSize: 15 },
});
