import { StyleSheet, Dimensions, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const { width, height } = Dimensions.get("window");

export const FRAME_W = width * 0.9;
export const FRAME_H = height * 0.65;

const HomeStyles = StyleSheet.create({
  // ═══════════════════════════════════════════════════════════════
  // HOME SCREEN — Light theme
  // ═══════════════════════════════════════════════════════════════

  homeContainer: {
    flex: 1,
    backgroundColor: COLORS.backgroundSoft,
  },

  // ── Header banner xanh lá primary ───────────────────────────────
  headerBanner: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 8 : 18,
    paddingBottom: 30,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  homeTextGroup: {
    flex: 1,
    paddingRight: 14,
  },
  homeGreeting: {
    color: COLORS.appTaglineColor, // #a5d6a7 — xanh nhạt trên nền dark
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  homeName: {
    color: COLORS.white,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  rolePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  roleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.secondary,
  },
  roleText: {
    color: COLORS.secondaryLight,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  profileButton: {
    alignItems: "center",
    gap: 5,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: COLORS.secondaryLight,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: COLORS.primary,
    fontSize: 15,
    fontWeight: "800",
  },
  profileButtonText: {
    color: COLORS.appTaglineColor,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.3,
  },

  // ── Stat row — nổi lên từ banner ────────────────────────────────
  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 16,
    marginTop: -18,
    marginBottom: 6,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.5,
    // color inject inline per card
  },
  statLabel: {
    color: COLORS.textGray,
    fontSize: 10,
    fontWeight: "500",
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  // ── Scroll content ───────────────────────────────────────────────
  homeContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 110,
  },

  // ── Section header ───────────────────────────────────────────────
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    color: COLORS.neutralDark,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.1,
  },
  sectionSub: {
    color: COLORS.textGray,
    fontSize: 12,
    fontWeight: "400",
  },

  // ── Action grid ──────────────────────────────────────────────────
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  actionCard: {
    width: "48.5%",
    backgroundColor: COLORS.cardBg,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  // Accent bar 3px trên đầu card, màu theo nhóm
  cardTopAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  actionIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    marginTop: 6, // chừa chỗ cho accent bar
  },
  actionLabel: {
    color: COLORS.neutralDark,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  actionSub: {
    color: COLORS.textGray,
    fontSize: 11,
    fontWeight: "400",
    marginTop: 3,
  },

  // ── Activity feed ────────────────────────────────────────────────
  activityCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  actDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  actTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.neutralDark,
  },
  actBadge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 8,
  },
  actBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  // Badge presets — textColor dùng cho Text, rest cho View
  badgeGreen: {
    backgroundColor: COLORS.successBg,
    textColor: COLORS.successAccent,
  },
  badgeAmber: {
    backgroundColor: COLORS.amberAccentBg,
    textColor: COLORS.amberAccentText,
  },
  badgeBlue: {
    backgroundColor: COLORS.blueAccentBg,
    textColor: COLORS.blueAccent,
  },

  // ── Empty state ──────────────────────────────────────────────────
  emptyState: {
    paddingVertical: 36,
    paddingHorizontal: 24,
    backgroundColor: COLORS.cardBg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    gap: 10,
  },
  emptyTitle: {
    color: COLORS.neutralDark,
    fontSize: 15,
    fontWeight: "700",
  },
  emptyText: {
    color: COLORS.textMuted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },

  customizeActionText: {
    color: COLORS.secondary,
    fontSize: 12,
    fontWeight: "700",
  },
  viewMoreButton: {
    alignSelf: "flex-start",
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: COLORS.secondaryLight,
  },
  viewMoreText: {
    color: COLORS.secondary,
    fontSize: 12,
    fontWeight: "700",
  },
  loadingActivity: {
    paddingVertical: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 32,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 18,
    maxHeight: "86%",
  },
  modalTitle: {
    color: COLORS.neutralDark,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 6,
  },
  modalSubtitle: {
    color: COLORS.textGray,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 14,
  },
  modalList: {
    marginBottom: 12,
  },
  modalListContent: {
    paddingBottom: 12,
  },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: COLORS.backgroundSoft,
    marginBottom: 10,
  },
  modalItemText: {
    color: COLORS.neutralDark,
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
    marginRight: 12,
  },
  modalItemAction: {
    color: COLORS.secondary,
    fontSize: 12,
    fontWeight: "700",
  },
  modalRemoveText: {
    color: COLORS.dangerAccent,
    fontSize: 12,
    fontWeight: "700",
  },
  modalSection: {
    marginTop: 16,
  },
  modalSectionTitle: {
    color: COLORS.neutralDark,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 10,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  modalCancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: COLORS.borderLight,
  },
  modalCancelText: {
    color: COLORS.neutralDark,
    fontSize: 13,
    fontWeight: "700",
  },

  // ── Floating Action Button ───────────────────────────────────────
  floatingAction: {
    position: "absolute",
    right: 18,
    bottom: Platform.OS === "ios" ? 100 : 88,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 13,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 10,
  },
  floatingText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: "700",
  },

  // ── Bottom tabs ──────────────────────────────────────────────────
  bottomTabsContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    paddingBottom: Platform.OS === "ios" ? 24 : 10,
    paddingTop: 8,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 10,
  },
  bottomTabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
  },
  bottomTabIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 2,
  },
  bottomTabIconActive: {
    backgroundColor: COLORS.greenSubtle,
  },
  bottomTabLabel: {
    color: COLORS.textGray,
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
  },
  bottomTabActive: {
    color: COLORS.secondary,
  },

  // ═══════════════════════════════════════════════════════════════
  // CAMERA SCREEN — giữ nguyên để không phá CameraPOD
  // ═══════════════════════════════════════════════════════════════

  container: { flex: 1, backgroundColor: "#000" },

  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.formSectionBg,
    paddingHorizontal: 32,
  },
  permissionIconWrap: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: COLORS.primaryLight,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: COLORS.secondary,
  },
  permissionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.white,
    marginBottom: 12,
  },
  permissionDesc: {
    fontSize: 15,
    color: COLORS.textGray,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 32,
  },
  btnPermission: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.secondary,
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 100,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  btnPermissionText: { color: COLORS.white, fontWeight: "700", fontSize: 16 },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  maskContainer: { ...StyleSheet.absoluteFillObject },
  maskTop: { flex: 1, width: "100%", backgroundColor: "rgba(0,0,0,0.65)" },
  maskBottom: { flex: 1, width: "100%", backgroundColor: "rgba(0,0,0,0.65)" },
  maskCenter: { flexDirection: "row", height: FRAME_H },
  maskSide: { flex: 1, backgroundColor: "rgba(0,0,0,0.65)" },

  scanFrame: {
    width: FRAME_W,
    height: FRAME_H,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  scanHint: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 14,
    fontWeight: "500",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: "hidden",
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 55 : 45,
    paddingBottom: 15,
    zIndex: 100,
  },
  headerBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  headerCenter: { flexDirection: "column", alignItems: "center" },
  headerTitle: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    color: COLORS.secondary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  queueBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  badge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: COLORS.error,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#000",
  },
  badgeText: { color: COLORS.white, fontSize: 10, fontWeight: "800" },

  corner: { position: "absolute", width: 40, height: 40, zIndex: 30 },
  cornerHorizontal: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 40,
    height: 4,
    backgroundColor: COLORS.secondary,
    borderRadius: 2,
  },
  cornerVertical: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 4,
    height: 40,
    backgroundColor: COLORS.secondary,
    borderRadius: 2,
  },

  bottomBar: {
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 45 : 30,
    paddingTop: 20,
    alignItems: "center",
    backgroundColor: "#000000",
    zIndex: 100,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginBottom: 20,
  },
  statChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statText: { fontSize: 12, fontWeight: "600" },

  shutterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
  },
  sideBtn: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  sideBtnLabel: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 10,
    marginTop: 4,
    fontWeight: "600",
  },
  shutterOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 4,
    borderColor: COLORS.white,
  },
  shutterInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
  },
  versionText: {
    color: "rgba(255,255,255,0.2)",
    fontSize: 10,
    marginTop: 15,
    fontWeight: "500",
  },

  // ═══════════════════════════════════════════════════════════════
  // BOTTOM SHEETS / MENU (dùng chung)
  // ═══════════════════════════════════════════════════════════════

  toastLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
  },
  menuSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.headerBg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === "ios" ? 40 : 24,
    paddingTop: 12,
    maxHeight: height * 0.85,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.3,
    elevation: 20,
  },
  sheetHandle: {
    width: 40,
    height: 5,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 20,
  },
  menuUserRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    padding: 12,
    borderRadius: 16,
  },
  menuAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  menuAvatarText: { color: COLORS.white, fontSize: 20, fontWeight: "800" },
  menuUserName: { fontSize: 16, fontWeight: "700", color: COLORS.white },
  menuUserRole: {
    fontSize: 13,
    color: COLORS.textGray,
    marginTop: 4,
    fontWeight: "500",
  },
  closeSheetBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  sheetDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    marginVertical: 10,
  },
  sheetSectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.textGray,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 16,
    marginBottom: 8,
    marginLeft: 4,
  },
  sheetItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  sheetIconBox: {
    width: 40,
    height: 40,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  sheetItemText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
    flex: 1,
  },
});

export default HomeStyles;
