import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  header: {
    flexDirection: "row",
    backgroundColor: PRIMARY,
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    zIndex: 10,
  },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { color: "white", fontSize: 16, fontWeight: "900" },
  headerSubtitle: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  headerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: "#EF4444",
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  headerBadgeText: { color: "#FFF", fontSize: 9, fontWeight: "900" },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  emptyText: {
    color: "#64748B",
    fontWeight: "700",
    marginTop: 12,
    textAlign: "center",
  },
  listContent: { padding: 16, paddingBottom: 30 },
  statsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 14,
  },
  statItem: { flex: 1, alignItems: "center" },
  statNum: { fontSize: 22, fontWeight: "900", color: PRIMARY, marginBottom: 4 },
  statLabel: { fontSize: 11, fontWeight: "700", color: "#64748B" },
  statDivider: { width: 1, backgroundColor: "#E2E8F0", alignSelf: "stretch" },
  progressSection: {},
  progressLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  progressLabel: { fontSize: 12, fontWeight: "700", color: "#475569" },
  progressPct: { fontSize: 12, fontWeight: "900", color: PRIMARY },
  progressBar: {
    height: 8,
    backgroundColor: "#F1F5F9",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 4 },
  extraBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F5F3FF",
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#DDD6FE",
  },
  extraBtnText: { flex: 1, fontSize: 14, fontWeight: "800", color: "#7C3AED" },
  extraBtnDesc: { fontSize: 11, fontWeight: "600", color: "#A78BFA" },
  listTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: "#475569",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  waybillCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  waybillCardDone: { borderColor: "#A7F3D0", backgroundColor: "#F0FDF4" },
  waybillTop: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  seqBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  seqText: { fontSize: 11, fontWeight: "900", color: "#64748B" },
  waybillMiddle: { flex: 1, marginRight: 8 },
  waybillCode: { fontSize: 13, fontWeight: "900", color: "#0F172A" },
  waybillName: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748B",
    marginTop: 2,
  },
  ocrBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: 1,
  },
  ocrBadgeText: { fontSize: 10, fontWeight: "900" },
  waybillBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 4,
  },
  waybillReceiverText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#94A3B8",
    flex: 1,
  },
  waybillArrow: { position: "absolute", right: 14, top: "50%" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === "ios" ? 40 : 24,
  },
  modalHeader: { alignItems: "center", marginBottom: 20 },
  modalHeaderIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#F5F3FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  modalTitle: { fontSize: 18, fontWeight: "900", color: "#0F172A" },
  modalSubtitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748B",
    marginTop: 4,
  },
  modalField: { marginBottom: 16 },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#475569",
    marginBottom: 8,
  },
  fieldInput: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    backgroundColor: "#F8FAFC",
  },
  modalActions: { flexDirection: "row", gap: 12, marginTop: 8 },
  cancelBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: { fontSize: 15, fontWeight: "800", color: "#64748B" },
  confirmBtn: {
    flex: 2,
    flexDirection: "row",
    borderRadius: 14,
    paddingVertical: 14,
    backgroundColor: "#7C3AED",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  confirmBtnText: { fontSize: 15, fontWeight: "900", color: "#FFF" },
});
