import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const PricingRulesStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    headerArea: { backgroundColor: COLORS.headerBg, paddingTop: 50, paddingBottom: 60, position: 'relative', overflow: 'hidden', zIndex: 1 },
    headerCircleDecoration: { position: 'absolute', top: -30, right: -60, width: 250, height: 250, borderRadius: 125, backgroundColor: 'rgba(255,255,255,0.08)' },
    headerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 },
    backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
    headerTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
    scrollViewWrapper: { flex: 1, zIndex: 10, marginTop: -35 },
    scrollContent: { padding: 15, paddingBottom: 100 },
    loadingOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(248, 249, 250, 0.7)', justifyContent: 'center', alignItems: 'center', zIndex: 20 },
    tabContainer: { flexDirection: 'row', backgroundColor: COLORS.white, borderRadius: 30, padding: 6, marginBottom: 20, borderWidth: 1, borderColor: '#edf1ed' },
    tab: { flex: 1, paddingVertical: 14, alignItems: 'center', borderRadius: 25 },
    tabActive: { backgroundColor: COLORS.secondary },
    tabText: { fontSize: 14, color: '#7b867e', fontWeight: '600' },
    tabTextActive: { color: '#FFF', fontWeight: 'bold' },
    card: { backgroundColor: COLORS.white, borderRadius: 20, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: '#edf1ed' },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    serviceBadge: { backgroundColor: COLORS.backgroundSoft, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
    serviceBadgeText: { color: COLORS.primary, fontSize: 13, fontWeight: 'bold' },
    priceText: { fontSize: 18, fontWeight: 'bold', color: COLORS.error },
    cardTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary, marginBottom: 4 },
    serviceCode: { fontSize: 13, color: '#7b867e' },
    divider: { height: 1, backgroundColor: '#edf1ed', marginVertical: 15 },
    rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    iconCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#edf8ef', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
    infoText: { color: '#7b867e', fontSize: 14, flex: 1 },
    statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10 },
    statusDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
    actionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#edf1ed' },
    actionBtnEdit: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#edf8ef', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
    actionBtnDelete: { backgroundColor: '#fee2e2', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, marginLeft: 10 },
    fab: { position: 'absolute', bottom: 30, right: 20, width: 64, height: 64, borderRadius: 32, backgroundColor: COLORS.secondary, justifyContent: 'center', alignItems: 'center', zIndex: 9999 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContainer: { backgroundColor: COLORS.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 25, maxHeight: '90%' },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.primary },
    label: { fontSize: 14, fontWeight: '600', color: COLORS.primary, marginBottom: 6 },
    input: { borderWidth: 1, borderColor: '#edf1ed', backgroundColor: COLORS.backgroundSoft, borderRadius: 12, paddingHorizontal: 15, height: 50, fontSize: 15, color: COLORS.primary, marginBottom: 15 },
    optionRow: { flexDirection: 'row', marginBottom: 15 },
    optionBtn: { flex: 1, marginHorizontal: 3, paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: '#d8e0d9', backgroundColor: COLORS.backgroundSoft, alignItems: 'center' },
    optionBtnActive: { backgroundColor: COLORS.secondary, borderColor: COLORS.secondary },
    optionBtnText: { color: '#6f7c72', fontWeight: '600', fontSize: 13 },
    optionBtnTextActive: { color: '#FFF', fontWeight: 'bold' },
    switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.backgroundSoft, padding: 15, borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: '#edf1ed' },
    submitBtn: { backgroundColor: COLORS.secondary, paddingVertical: 16, borderRadius: 16, alignItems: 'center', marginBottom: 20 },
});

export default PricingRulesStyles;
