import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    blueHeader: {
        backgroundColor: COLORS.primary,
        height: 180,
        alignItems: 'center',
        paddingTop: 50,
        position: 'relative',
        overflow: 'hidden',
        zIndex: 1,
    },
    headerCircleDecoration1: {
        position: 'absolute',
        top: -50,
        right: -50,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    headerCircleDecoration2: {
        position: 'absolute',
        bottom: -30,
        left: -40,
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    headerTitle: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    scrollView: {
        flex: 1,
        marginTop: -60,
        zIndex: 10,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    profileCard: {
        backgroundColor: COLORS.white,
        marginHorizontal: 20,
        borderRadius: 24,
        padding: 20,
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 15,
        shadowOffset: { width: 0, height: 5 },
    },
    avatarContainer: {
        position: 'relative',
        marginTop: 10,
        marginBottom: 15,
    },
    avatarPlaceholder: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: COLORS.backgroundSoft,
        borderWidth: 4,
        borderColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    avatarText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    editBadge: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        backgroundColor: COLORS.primary,
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: COLORS.white,
        elevation: 3,
    },
    nameText: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    roleText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e8f5e9',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginTop: 10,
        marginBottom: 20,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: COLORS.secondary,
        marginRight: 6,
    },
    statusText: {
        color: COLORS.secondary,
        fontSize: 12,
        fontWeight: 'bold',
    },
    infoList: {
        width: '100%',
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        paddingTop: 20,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
        paddingBottom: 15,
    },
    iconWrap: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: COLORS.inputBg,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    infoLabel: {
        fontSize: 12,
        color: '#999',
        marginBottom: 4,
    },
    infoValue: {
        fontSize: 15,
        color: '#333',
        fontWeight: '600',
    },
    menuCard: {
        backgroundColor: COLORS.white,
        marginHorizontal: 20,
        marginTop: 20,
        borderRadius: 20,
        padding: 20,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    codHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    codIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#fff3e0',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    codTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#333',
    },
    codContent: {
        backgroundColor: COLORS.backgroundSoft,
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    codAmount: {
        fontSize: 32,
        fontWeight: 'bold',
        color: COLORS.error,
        marginBottom: 5,
    },
    codDesc: {
        color: '#666',
        fontSize: 13,
    },
    logoutBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fdecea',
        marginHorizontal: 20,
        marginTop: 30,
        paddingVertical: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#f5c6cb',
    },
    logoutText: {
        color: COLORS.logOut,
        fontWeight: 'bold',
        fontSize: 16,
        marginLeft: 10,
    },
    versionText: {
        textAlign: 'center',
        marginTop: 20,
        color: '#999',
        fontSize: 12,
        fontWeight: '500',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: COLORS.white,
        width: '85%',
        padding: 25,
        borderRadius: 24,
        alignItems: 'center',
        elevation: 5,
    },
    modalWarningIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#fdecea',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
    },
    modalDesc: {
        textAlign: 'center',
        color: '#666',
        marginBottom: 25,
        fontSize: 14,
        lineHeight: 22,
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalBtnCancel: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: '#f5f5f5',
        marginRight: 8,
        alignItems: 'center',
    },
    modalBtnCancelText: {
        color: '#333',
        fontWeight: 'bold',
        fontSize: 15,
    },
    modalBtnConfirm: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        backgroundColor: COLORS.logOut,
        marginLeft: 8,
        alignItems: 'center',
        elevation: 2,
    },
    modalBtnConfirmText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
    },
});
