import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const ScanManifestLoadStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  cameraArea: { height: "50%", position: "relative" },
  camHeader: {
    position: "absolute",
    top: 0,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  liveBadge: {
    borderWidth: 1,
    borderColor: COLORS.secondary,
    backgroundColor: "rgba(76,175,80,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  cameraOverlayLock: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  lockText: {
    color: "rgba(255,255,255,0.7)",
    marginTop: 15,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  manualInputContainer: {
    position: "absolute",
    bottom: 0,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  inputBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(30, 41, 59, 0.85)",
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#334155",
  },
  inputCam: { flex: 1, color: "#FFF", fontSize: 15 },
  sendBtn: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomSheet: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -20,
    position: "relative",
  },
  configArea: { padding: 25, paddingBottom: 50 },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 25,
  },
  iconCirclePrimary: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e8f5e9",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  configTitle: { fontSize: 16, fontWeight: "bold", color: COLORS.primary },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.primary,
    marginBottom: 8,
  },
  inputForm: {
    borderWidth: 1,
    borderColor: "#e7ece8",
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
    backgroundColor: COLORS.backgroundSoft,
    marginBottom: 20,
    fontSize: 15,
    color: COLORS.primary,
  },
  selectorBtn: {
    borderWidth: 1,
    borderColor: "#e7ece8",
    borderRadius: 12,
    backgroundColor: COLORS.backgroundSoft,
    minHeight: 52,
    paddingHorizontal: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  selectorBtnText: {
    fontSize: 15,
    color: COLORS.primary,
    fontWeight: "600",
    flex: 1,
    marginRight: 10,
  },
  selectorPlaceholder: { color: "#7b867e", fontWeight: "normal" },
  startBtn: {
    flexDirection: "row",
    backgroundColor: COLORS.secondary,
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  startBtnText: { color: "#FFF", fontWeight: "bold", fontSize: 16 },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderColor: "#e7ece8",
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 2,
  },
  sheetSub: { fontSize: 13, color: "#7b867e" },
  badgeCount: {
    backgroundColor: COLORS.secondary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  listContent: { padding: 20, paddingTop: 5, paddingBottom: 100 },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginBottom: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#edf1ed",
  },
  firstItem: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  leftInfo: { flexDirection: "row", alignItems: "center" },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    backgroundColor: "#e8f5e9",
  },
  itemCode: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 2,
  },
  itemCodePrimary: { color: COLORS.white },
  itemTime: { fontSize: 13, color: "#7b867e" },
  itemTimePrimary: { color: "rgba(255,255,255,0.82)" },
  emptyWrap: { alignItems: "center", marginTop: 40 },
  emptyText: {
    color: "#7b867e",
    marginTop: 10,
    fontSize: 14,
    fontStyle: "italic",
  },
  summaryFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.background,
    padding: 15,
    borderTopWidth: 1,
    borderColor: "#e7ece8",
  },
  finishBtn: {
    flexDirection: "row",
    backgroundColor: COLORS.secondary,
    paddingVertical: 16,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  finishBtnText: { color: "#FFF", fontWeight: "bold", fontSize: 16 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "75%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.primary },
  optionItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2ee",
  },
  optionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 2,
  },
  optionSub: { fontSize: 13, color: "#7b867e" },
});

export default ScanManifestLoadStyles;
