import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const ScanManifestUnloadStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#000' },
    cameraArea: { height: '50%', position: 'relative' },
    camHeader: {
        position: 'absolute',
        top: 50,
        left: 20,
        right: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    liveBadge: {
        borderWidth: 1,
        borderColor: COLORS.secondary,
        backgroundColor: 'rgba(76,175,80,0.2)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    cameraOverlayLock: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#1E293B',
        justifyContent: 'center',
        alignItems: 'center',
    },
    lockText: { color: 'rgba(255,255,255,0.65)', marginTop: 15, fontWeight: 'bold', letterSpacing: 1 },
    bottomSheet: {
        flex: 1,
        backgroundColor: COLORS.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        marginTop: -20,
        position: 'relative',
    },
    configArea: { padding: 25, paddingBottom: 50 },
    cardHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 25 },
    iconCircleSuccess: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#ecfdf5',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    configTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary },
    label: { fontSize: 13, fontWeight: '600', color: COLORS.primary, marginBottom: 8 },
    selectorBtn: {
        borderWidth: 1,
        borderColor: '#e7ece8',
        borderRadius: 12,
        backgroundColor: COLORS.backgroundSoft,
        minHeight: 52,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 30,
    },
    selectorBtnText: { fontSize: 15, color: COLORS.primary, fontWeight: '600', flex: 1, marginRight: 10 },
    selectorPlaceholder: { color: '#7b867e', fontWeight: 'normal' },
    startBtn: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        paddingVertical: 16,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    startBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
    sheetHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderColor: '#e7ece8',
    },
    sheetTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary, marginBottom: 2 },
    sheetSub: { fontSize: 14, color: '#7b867e' },
    unlockBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fee2e2',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
    },
    listContent: { padding: 20, paddingTop: 5, paddingBottom: 100 },
    listItem: {
        borderRadius: 16,
        marginBottom: 12,
        padding: 16,
        borderWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    scannedItem: { backgroundColor: '#ecfdf5', borderColor: COLORS.secondary },
    pendingItem: { backgroundColor: COLORS.white, borderColor: '#edf1ed' },
    leftInfo: { flexDirection: 'row', alignItems: 'center' },
    iconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    itemCode: { fontSize: 11, fontWeight: 'bold', marginBottom: 2 },
    itemTime: { fontSize: 16, fontWeight: 'bold' },
    emptyText: { textAlign: 'center', color: '#7b867e', marginTop: 40, fontStyle: 'italic' },
    summaryFooter: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: COLORS.background,
        padding: 15,
        borderTopWidth: 1,
        borderColor: '#e7ece8',
    },
    finishBtn: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        paddingVertical: 16,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    finishBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    modalContent: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
        maxHeight: '75%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    modalTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.primary },
    optionItem: {
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#eef2ee',
    },
    optionTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.primary, marginBottom: 2 },
    optionSub: { fontSize: 13, color: '#7b867e' },
});

export default ScanManifestUnloadStyles;
