import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const ScanInHubStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.primary,
    },
    cameraArea: {
        height: '50%',
        position: 'relative',
        backgroundColor: '#000',
    },
    camHeader: {
        position: 'absolute',
        top: 50,
        left: 20,
        right: 20,
        zIndex: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    backBtn: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    liveBadge: {
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 12,
        backgroundColor: 'rgba(76, 175, 80, 0.16)',
        borderWidth: 1,
        borderColor: COLORS.secondary,
    },
    liveText: {
        color: COLORS.secondary,
        fontSize: 12,
        fontWeight: 'bold',
    },
    manualInputContainer: {
        position: 'absolute',
        left: 20,
        right: 20,
        bottom: 26,
        flexDirection: 'row',
        alignItems: 'center',
    },
    inputBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        height: 50,
        borderRadius: 12,
        backgroundColor: 'rgba(0,0,0,0.45)',
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.12)',
    },
    input: {
        flex: 1,
        color: COLORS.white,
        fontSize: 15,
    },
    sendBtn: {
        width: 50,
        height: 50,
        borderRadius: 12,
        backgroundColor: COLORS.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    contentArea: {
        flex: 1,
        marginTop: -20,
        backgroundColor: COLORS.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        overflow: 'hidden',
    },
    headerCard: {
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    countBadge: {
        marginLeft: 10,
        minWidth: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: COLORS.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    countBadgeText: {
        color: COLORS.white,
        fontSize: 12,
        fontWeight: 'bold',
    },
    clearBtn: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#dfe6dc',
        backgroundColor: COLORS.backgroundSoft,
    },
    clearBtnText: {
        color: '#55635b',
        fontSize: 13,
        fontWeight: '600',
    },
    listContent: {
        paddingHorizontal: 20,
        paddingBottom: 105,
        paddingTop: 6,
    },
    listItem: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#edf1ed',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 1,
    },
    firstItem: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
    },
    firstItemTag: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        paddingHorizontal: 15,
        paddingVertical: 6,
        backgroundColor: 'rgba(255,255,255,0.08)',
        flexDirection: 'row',
        alignItems: 'center',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
    },
    tagDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: COLORS.white,
        marginRight: 6,
    },
    firstItemTagText: {
        color: COLORS.white,
        fontSize: 11,
        fontWeight: 'bold',
    },
    itemContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    firstItemContent: {
        paddingTop: 18,
    },
    leftInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 12,
    },
    iconCircle: {
        width: 34,
        height: 34,
        borderRadius: 17,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#edf8ef',
        marginRight: 12,
    },
    iconCirclePrimary: {
        backgroundColor: 'rgba(255,255,255,0.14)',
    },
    itemCode: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#233127',
        marginBottom: 3,
    },
    itemCodePrimary: {
        color: COLORS.white,
    },
    itemTime: {
        fontSize: 12,
        color: '#7a857d',
    },
    itemTimePrimary: {
        color: 'rgba(255,255,255,0.82)',
    },
    rightInfo: {
        alignItems: 'flex-end',
    },
    itemWeight: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    itemWeightPrimary: {
        color: COLORS.white,
    },
    itemWeightSub: {
        fontSize: 12,
        color: '#7a857d',
        marginTop: 2,
    },
    itemWeightSubPrimary: {
        color: 'rgba(255,255,255,0.82)',
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 50,
    },
    emptyText: {
        marginTop: 12,
        color: '#7a857d',
        fontSize: 14,
    },
    summaryFooter: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: COLORS.backgroundSoft,
        borderTopWidth: 1,
        borderTopColor: '#e4ebe5',
        paddingHorizontal: 20,
        paddingVertical: 18,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    summaryLabel: {
        fontSize: 14,
        color: '#657067',
    },
    summaryValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
});

export default ScanInHubStyles;
