import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from "../constants/theme";

const ScanManifestLoadStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  flex: { flex: 1 },
  cameraArea: { flex: 1, position: "relative" },
  cameraFrame: {
    flex: 1,
    marginHorizontal: SPACING.md,
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 2,
    borderColor: COLORS.primary,
    overflow: "hidden",
  },
  camHeader: {
    position: "absolute",
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backBtn: {
    width: TOUCH_TARGET.androidMin,
    height: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.inputWrapperBg,
    justifyContent: "center",
    alignItems: "center",
  },
  liveBadge: {
    borderWidth: 1,
    borderColor: COLORS.secondary,
    backgroundColor: COLORS.successBg,
    borderRadius: BORDER_RADIUS.round,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  liveText: {
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  cameraOverlayLock: {
    flex: 1,
    backgroundColor: COLORS.neutralDark,
    justifyContent: "center",
    alignItems: "center",
    gap: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
  },
  lockText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    textTransform: "uppercase",
  },
  bottomSheet: {
    backgroundColor: COLORS.cardBg,
    borderTopLeftRadius: BORDER_RADIUS.xl,
    borderTopRightRadius: BORDER_RADIUS.xl,
    marginTop: -SPACING.md,
    paddingTop: SPACING.md,
    gap: SPACING.md,
    ...SHADOWS.md,
  },
  configArea: { paddingHorizontal: SPACING.md, gap: SPACING.sm },
  cardHeaderRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  iconCirclePrimary: {
    width: TOUCH_TARGET.androidMin,
    height: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.secondaryLight,
    justifyContent: "center",
    alignItems: "center",
  },
  configTitle: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.subtitle,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  label: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    textTransform: "uppercase",
  },
  selectorBtn: {
    minHeight: TOUCH_TARGET.androidMin,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.backgroundSoft,
    paddingHorizontal: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectorBtnText: {
    flex: 1,
    marginRight: SPACING.sm,
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  selectorPlaceholder: { color: COLORS.textMuted, fontWeight: TYPOGRAPHY.fontWeight.regular },
  sheetHeader: {
    paddingHorizontal: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sheetTitle: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  sheetSub: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  statRow: { flexDirection: "row", gap: SPACING.sm, paddingHorizontal: SPACING.md },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    padding: SPACING.sm,
    ...SHADOWS.sm,
  },
  statLabel: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  statValue: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.heading,
    lineHeight: TYPOGRAPHY.lineHeight.heading,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  listContent: { paddingHorizontal: SPACING.md, paddingBottom: SPACING.xxl, gap: SPACING.sm },
  listItem: {
    minHeight: TOUCH_TARGET.androidMin,
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    ...SHADOWS.sm,
  },
  leftInfo: { flexDirection: "row", alignItems: "center", gap: SPACING.sm, flex: 1 },
  iconCircle: {
    width: TOUCH_TARGET.androidMin,
    height: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.secondaryLight,
  },
  itemCode: {
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  itemTime: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  removeBtn: {
    minWidth: TOUCH_TARGET.androidMin,
    minHeight: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.errorBg,
  },
  emptyWrap: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.lg },
  footer: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
  },
  finishBtn: { minHeight: TOUCH_TARGET.androidMin },
  manualRow: { flexDirection: "row", gap: SPACING.sm, paddingHorizontal: SPACING.md },
  manualInput: { flex: 1 },
  sendBtn: {
    minWidth: TOUCH_TARGET.androidMin,
    minHeight: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.inputWrapperBg,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.cardBg,
    borderTopLeftRadius: BORDER_RADIUS.xl,
    borderTopRightRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg,
    maxHeight: "75%",
  },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: SPACING.sm },
  modalTitle: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.subtitle,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  optionItem: { paddingVertical: SPACING.md, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  optionTitle: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  optionSub: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
});

export default ScanManifestLoadStyles;
