import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const PRIMARY = COLORS.primary || "#1B5E20";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  header: {
    flexDirection: "row",
    backgroundColor: PRIMARY,
    paddingTop: Platform.OS === "ios" ? 55 : 35,
    paddingHorizontal: 20,
    paddingBottom: 22,
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomLeftRadius: 42,
    borderBottomRightRadius: 42,
    shadowColor: "#ebebeb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    zIndex: 10,
  },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { color: "#FFF", fontSize: 18, fontWeight: "900" },
  headerBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchSection: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchRow: { flexDirection: "row", gap: 10 },
  searchInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    minHeight: 48,
  },
  searchInput: { flex: 1, fontSize: 15, color: "#0F172A", fontWeight: "700" },
  searchBtn: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 48,
  },
  searchBtnText: { color: "#FFF", fontWeight: "900", fontSize: 15 },
  statusCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#64748B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  statusCardLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  statusIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#F0FDF4",
    justifyContent: "center",
    alignItems: "center",
  },
  statusLabel: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "700",
    marginBottom: 4,
  },
  statusValue: { fontSize: 16, fontWeight: "900", color: PRIMARY },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#0F172A",
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 12,
  },
  timelineContainer: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    backgroundColor: "#FFFFFF",
    marginHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingVertical: 16,
  },
  timelineRow: { flexDirection: "row", minHeight: 50 },
  timelineLeft: {
    width: 64,
    alignItems: "flex-end",
    paddingRight: 12,
    paddingTop: 2,
  },
  timeText: { fontSize: 14, fontWeight: "900", color: "#0F172A" },
  dateText: { fontSize: 11, color: "#64748B", fontWeight: "700", marginTop: 2 },
  timelineCenter: { width: 20, alignItems: "center" },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#CBD5E1",
    marginTop: 5,
    zIndex: 2,
  },
  timelineDotActive: {
    backgroundColor: PRIMARY,
    width: 14,
    height: 14,
    borderRadius: 7,
    shadowColor: PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  timelineLineTop: {
    position: "absolute",
    top: 0,
    bottom: "80%",
    width: 2,
    backgroundColor: "#E2E8F0",
  },
  timelineLineBottom: {
    position: "absolute",
    top: 15,
    bottom: -10,
    width: 2,
    backgroundColor: "#E2E8F0",
  },
  timelineRight: { flex: 1, paddingLeft: 12, paddingBottom: 24 },
  actionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#334155",
    marginBottom: 4,
  },
  actionTextActive: { color: PRIMARY, fontWeight: "900" },
  detailText: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 2,
    fontWeight: "600",
  },
  noteText: {
    fontSize: 13,
    color: "#D97706",
    fontStyle: "italic",
    marginTop: 2,
    fontWeight: "700",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  emptyIconBox: {
    width: 66,
    height: 66,
    borderRadius: 22,
    backgroundColor: "rgba(241,245,249,0.8)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    fontWeight: "600",
  },
});
