import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from "../constants/theme";

const ShopStatementStyles = StyleSheet.create({
  flex1: { flex: 1 },
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  headerArea: { backgroundColor: COLORS.headerBg, paddingTop: SPACING.lg, paddingBottom: SPACING.xl },
  headerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: SPACING.md },
  backBtn: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.primaryLight, justifyContent: "center", alignItems: "center" },
  headerTitle: { color: COLORS.white, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  headerRightPlaceholder: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin },
  contentWrapper: { flex: 1, marginTop: -SPACING.md, paddingHorizontal: SPACING.md, gap: SPACING.md },
  card: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, gap: SPACING.sm, ...SHADOWS.sm },
  label: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold, textTransform: "uppercase" },
  mockInput: { minHeight: TOUCH_TARGET.androidMin, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: COLORS.backgroundSoft, borderRadius: BORDER_RADIUS.md, paddingHorizontal: SPACING.md, borderWidth: 1, borderColor: COLORS.borderLight },
  textMain: { color: COLORS.textMain, fontSize: TYPOGRAPHY.fontSize.body, lineHeight: TYPOGRAPHY.lineHeight.body, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  textSub: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  searchIconWrap: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, backgroundColor: COLORS.greenSubtle, justifyContent: "center", alignItems: "center" },
  infoCard: { backgroundColor: COLORS.successBg, borderRadius: BORDER_RADIUS.md, padding: SPACING.sm, borderWidth: 1, borderColor: COLORS.successAccent, gap: SPACING.sm },
  infoRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  infoText: { color: COLORS.neutralMid, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium, flex: 1 },
  boldPrimary: { color: COLORS.primary, fontWeight: TYPOGRAPHY.fontWeight.bold },
  boldSecondary: { color: COLORS.secondary, fontWeight: TYPOGRAPHY.fontWeight.bold },
  statementTypeRow: { flexDirection: "row", gap: SPACING.sm },
  statementTypeButton: { flex: 1, minHeight: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.backgroundSoft, alignItems: "center", justifyContent: "center" },
  statementTypeButtonActive: { backgroundColor: COLORS.secondary, borderColor: COLORS.secondary },
  statementTypeButtonLabel: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  statementTypeButtonLabelActive: { color: COLORS.white },
  submitBtn: { minHeight: TOUCH_TARGET.androidMin },
  resultTicket: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, overflow: "hidden", ...SHADOWS.sm },
  ticketTop: { padding: SPACING.lg, alignItems: "center", backgroundColor: COLORS.successBg, gap: SPACING.xs },
  successCircle: { width: SPACING.xxl, height: SPACING.xxl, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.successAccent, justifyContent: "center", alignItems: "center" },
  resTitle: { color: COLORS.successAccent, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  resCode: { color: COLORS.neutralMid, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  ticketBottom: { padding: SPACING.lg, alignItems: "center", gap: SPACING.sm },
  rowMoney: { width: "100%", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  moneyLabel: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  moneyCod: { color: COLORS.successAccent, fontSize: TYPOGRAPHY.fontSize.headingSm, lineHeight: TYPOGRAPHY.lineHeight.headingSm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  moneyFee: { color: COLORS.error, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  downloadRow: { flexDirection: "row", gap: SPACING.sm, width: "100%" },
  downloadBtn: { flex: 1, minHeight: TOUCH_TARGET.androidMin },
  modalOverlay: { flex: 1, backgroundColor: COLORS.inputWrapperBg, justifyContent: "flex-end" },
  modalContainer: { backgroundColor: COLORS.cardBg, borderTopLeftRadius: BORDER_RADIUS.xl, borderTopRightRadius: BORDER_RADIUS.xl, padding: SPACING.lg, maxHeight: "85%" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: SPACING.md },
  modalTitle: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  searchWrap: { marginBottom: SPACING.sm },
  searchItem: { paddingVertical: SPACING.md, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  searchItemRow: { flexDirection: "row", alignItems: "center" },
  custIcon: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, backgroundColor: COLORS.greenSubtle, justifyContent: "center", alignItems: "center", marginRight: SPACING.sm },
  searchName: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  searchMeta: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  emptyText: { textAlign: "center", marginTop: SPACING.lg, color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  skeletonWrap: { padding: SPACING.md, gap: SPACING.sm },
  skeletonLine: { marginTop: SPACING.sm },
});

export default ShopStatementStyles;
