import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const ShopStatementStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    headerArea: {
        backgroundColor: COLORS.headerBg,
        paddingTop: 50,
        paddingBottom: 60,
        position: 'relative',
        overflow: 'hidden',
        zIndex: 1,
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -30,
        right: -60,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    headerTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.15)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
    contentWrapper: {
        flex: 1,
        zIndex: 10,
        marginTop: -35,
        paddingHorizontal: 15,
    },
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#edf1ed',
    },
    label: { fontSize: 14, fontWeight: 'bold', color: COLORS.primary, marginBottom: 12 },
    mockInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: COLORS.backgroundSoft,
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e7ece8',
        marginBottom: 20,
    },
    textMain: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary, marginBottom: 4 },
    textSub: { fontSize: 13, color: '#7b867e' },
    searchIconWrap: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#edf8ef',
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoCard: {
        backgroundColor: '#edf8ef',
        padding: 15,
        borderRadius: 12,
        marginBottom: 25,
        borderWidth: 1,
        borderColor: COLORS.secondary,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#d8e7d9',
        paddingBottom: 12,
    },
    infoText: { color: '#6f7c72', fontSize: 14, flex: 1 },
    submitBtn: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        paddingVertical: 16,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    submitBtnDisabled: { backgroundColor: '#94A3B8' },
    submitBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
    resultTicket: {
        backgroundColor: COLORS.white,
        borderRadius: 20,
        marginTop: 25,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#edf1ed',
    },
    ticketTop: { padding: 25, alignItems: 'center', backgroundColor: '#edf8ef' },
    successCircle: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: COLORS.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
    },
    resTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.secondary, marginBottom: 5 },
    resCode: { fontSize: 14, color: '#6f7c72', fontWeight: '500' },
    ticketDivider: { height: 30, backgroundColor: COLORS.white, position: 'relative', justifyContent: 'center' },
    ticketNotchLeft: { position: 'absolute', left: -15, width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.background },
    ticketNotchRight: { position: 'absolute', right: -15, width: 30, height: 30, borderRadius: 15, backgroundColor: COLORS.background },
    dashedLine: { height: 1, borderWidth: 1, borderColor: '#e7ece8', borderStyle: 'dashed', marginHorizontal: 20 },
    ticketBottom: { padding: 25, paddingTop: 10, alignItems: 'center', backgroundColor: COLORS.white },
    resAmountLabel: { fontSize: 13, color: '#6f7c72', fontWeight: '600', letterSpacing: 1, marginBottom: 5 },
    resAmountValue: { fontSize: 32, fontWeight: 'bold', color: COLORS.error, marginBottom: 25 },
    downloadBtn: {
        flexDirection: 'row',
        backgroundColor: COLORS.secondary,
        paddingVertical: 14,
        paddingHorizontal: 25,
        borderRadius: 30,
        alignItems: 'center',
        width: '100%',
        justifyContent: 'center',
    },
    downloadText: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContainer: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
        maxHeight: '85%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.primary },
    searchWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.backgroundSoft,
        borderRadius: 12,
        height: 54,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e7ece8',
    },
    searchInput: { flex: 1, fontSize: 15, color: COLORS.primary },
    searchItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#edf1ed' },
    custIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#edf8ef',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
});

export default ShopStatementStyles;
