import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from '../constants/theme';

const StaffManagementStyles = StyleSheet.create({
  flex1: { flex: 1 },
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  headerArea: { backgroundColor: COLORS.headerBg, paddingTop: SPACING.lg, paddingBottom: SPACING.lg, paddingHorizontal: SPACING.md },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  backBtn: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.primaryLight, justifyContent: 'center', alignItems: 'center' },
  headerTitle: { color: COLORS.white, fontSize: TYPOGRAPHY.fontSize.headingSm, lineHeight: TYPOGRAPHY.lineHeight.headingSm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  headerRightPlaceholder: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin },
  content: { flex: 1, marginTop: -SPACING.md, paddingHorizontal: SPACING.md, gap: SPACING.md },
  toolbar: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
  searchInput: { flex: 1 },
  filterBtn: { minWidth: TOUCH_TARGET.androidMin, minHeight: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.cardBg, justifyContent: 'center', alignItems: 'center' },
  summaryCard: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', ...SHADOWS.sm },
  summaryText: { color: COLORS.neutralMid, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  summaryValue: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.headingSm, lineHeight: TYPOGRAPHY.lineHeight.headingSm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  listContent: { paddingBottom: SPACING.xxl, gap: SPACING.sm },
  card: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, borderWidth: 1, borderColor: COLORS.borderLight, ...SHADOWS.sm },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACING.sm },
  staffInfo: { flex: 1 },
  staffName: { color: COLORS.neutralDark, fontSize: TYPOGRAPHY.fontSize.body, lineHeight: TYPOGRAPHY.lineHeight.body, fontWeight: TYPOGRAPHY.fontWeight.bold },
  staffMeta: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  toggleBtn: { minWidth: TOUCH_TARGET.androidMin, minHeight: TOUCH_TARGET.androidMin, justifyContent: 'center', alignItems: 'center' },
  divider: { height: SPACING.hairline, backgroundColor: COLORS.borderLight, marginVertical: SPACING.sm },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  roleBadge: { paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.primaryLight },
  roleText: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  statusActive: { color: COLORS.successAccent, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  statusInactive: { color: COLORS.error, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  addFooter: { paddingHorizontal: SPACING.md, paddingTop: SPACING.sm },
  addFooterSafe: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: COLORS.backgroundSoft },
  addBtn: { minHeight: TOUCH_TARGET.androidMin, ...SHADOWS.lg },
  modalOverlay: { flex: 1, backgroundColor: COLORS.inputWrapperBg, justifyContent: 'flex-end' },
  modalContainer: { backgroundColor: COLORS.cardBg, borderTopLeftRadius: BORDER_RADIUS.xl, borderTopRightRadius: BORDER_RADIUS.xl, padding: SPACING.lg, maxHeight: '85%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.md },
  modalTitle: { color: COLORS.neutralDark, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  formContent: { gap: SPACING.sm, paddingBottom: SPACING.md },
  pickerWrap: { backgroundColor: COLORS.backgroundSoft, borderRadius: BORDER_RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight, overflow: 'hidden' },
  modalButton: { minHeight: TOUCH_TARGET.androidMin },
});

export default StaffManagementStyles;
