import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from '../constants/theme';

const TaskDetailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerArea: { backgroundColor: COLORS.headerBg, paddingTop: SPACING.lg, paddingBottom: SPACING.lg },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: SPACING.md },
  iconBtn: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.primaryLight, justifyContent: 'center', alignItems: 'center' },
  headerTitleWrap: { alignItems: 'center' },
  headerSub: { color: COLORS.greenSubtleText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  headerTitle: { color: COLORS.white, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  badgeRow: { flexDirection: 'row', paddingHorizontal: SPACING.md, marginTop: SPACING.sm, justifyContent: 'center', alignItems: 'center', gap: SPACING.sm },
  expressBadge: { backgroundColor: COLORS.warningBg, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.round },
  expressText: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  statusBadge: { paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.round, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.white },
  statusText: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  customerBar: { backgroundColor: COLORS.cardBg, marginHorizontal: SPACING.md, marginTop: -SPACING.md, padding: SPACING.md, borderRadius: BORDER_RADIUS.lg, borderWidth: 1, borderColor: COLORS.borderLight, zIndex: 10, ...SHADOWS.sm },
  customerHeader: { flexDirection: 'row', alignItems: 'center' },
  custInfo: { flex: 1 },
  custName: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.body, lineHeight: TYPOGRAPHY.lineHeight.body, fontWeight: TYPOGRAPHY.fontWeight.bold },
  custPhone: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  actionBtnCall: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginLeft: SPACING.sm },
  actionBtnMap: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, backgroundColor: COLORS.greenSubtle, justifyContent: 'center', alignItems: 'center', marginLeft: SPACING.sm },
  divider: { height: SPACING.hairline, backgroundColor: COLORS.borderLight, marginVertical: SPACING.sm },
  addressRow: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm },
  addressText: { flex: 1, color: COLORS.neutralMid, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.regular },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: SPACING.md, paddingTop: SPACING.md, paddingBottom: SPACING.xxl, gap: SPACING.md },
  card: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, gap: SPACING.sm, ...SHADOWS.sm },
  infoGrid: { flexDirection: 'row', gap: SPACING.sm },
  codBox: { flex: 1, backgroundColor: COLORS.warningBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, borderWidth: 1, borderColor: COLORS.amberAccentBg },
  codLabel: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  codValue: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.headingSm, lineHeight: TYPOGRAPHY.lineHeight.headingSm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  codUnit: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  rightStats: { flex: 1, gap: SPACING.sm },
  statBox: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, borderWidth: 1, borderColor: COLORS.borderLight, ...SHADOWS.sm },
  statLabel: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  statValue: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.body, lineHeight: TYPOGRAPHY.lineHeight.body, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  noteLabel: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  noteText: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.regular },
  timelineHeaderRow: { flexDirection: 'row', alignItems: 'center', paddingBottom: SPACING.sm, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight, gap: SPACING.sm },
  dotPrimaryTitle: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.secondary },
  timelineTitle: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  trackItemContainer: { flexDirection: 'row' },
  timeline: { alignItems: 'center', width: SPACING.lg },
  timelineDotActiveWrap: { width: SPACING.md, height: SPACING.md, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.secondaryLight, justifyContent: 'center', alignItems: 'center' },
  timelineDotActive: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.secondary },
  timelineDotPast: { width: SPACING.md_sm, height: SPACING.md_sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.white, borderWidth: 2, borderColor: COLORS.secondary, marginTop: SPACING.xs },
  timelineDotStart: { width: SPACING.md_sm, height: SPACING.md_sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.white, borderWidth: 2, borderColor: COLORS.borderLight, marginTop: SPACING.xs },
  timelineLine: { flex: 1, width: SPACING.xxs, backgroundColor: COLORS.borderLight },
  trackItem: { paddingLeft: SPACING.sm, paddingBottom: SPACING.md, flex: 1 },
  trackStatus: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  trackTime: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  emptyText: { textAlign: 'center', color: COLORS.textMuted, marginTop: SPACING.sm, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  actionSection: { backgroundColor: COLORS.white, borderTopWidth: 1, borderTopColor: COLORS.borderLight, paddingHorizontal: SPACING.md, paddingTop: SPACING.sm, gap: SPACING.sm },
  actionRow: { flexDirection: 'row', gap: SPACING.sm },
  actionBtn: { flex: 1, minHeight: TOUCH_TARGET.androidMin },
  transferModalOverlay: { flex: 1, backgroundColor: COLORS.inputWrapperBg, justifyContent: 'center', paddingHorizontal: SPACING.md },
  transferModalContent: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.xl, padding: SPACING.lg, gap: SPACING.sm, ...SHADOWS.md },
  transferFormContent: { gap: SPACING.sm, paddingBottom: SPACING.md },
  transferModalTitle: { color: COLORS.neutralDark, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  transferTypeRow: { flexDirection: 'row', gap: SPACING.sm },
  transferTypeBtn: { flex: 1, minHeight: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.cardBg, alignItems: 'center', justifyContent: 'center' },
  transferTypeBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  transferTypeText: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  transferTypeTextActive: { color: COLORS.white },
  transferActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: SPACING.sm },
  transferReasonInput: { minHeight: SPACING.xxl + SPACING.lg, textAlignVertical: 'top' },
  transferActionBtn: { minHeight: TOUCH_TARGET.androidMin },
  skeletonWrap: { gap: SPACING.md },
  skeletonLine: { marginTop: SPACING.sm },
});

export default TaskDetailStyles;

