import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const TaskDetailStyles = StyleSheet.create({
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    container: { flex: 1, backgroundColor: COLORS.background },
    headerArea: {
        backgroundColor: COLORS.headerBg,
        paddingTop: 50,
        paddingBottom: 40,
        position: 'relative',
        overflow: 'hidden',
        zIndex: 1,
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -30,
        right: -60,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20 },
    iconBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.15)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerSub: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: '600', marginBottom: 2 },
    headerTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
    badgeRow: { flexDirection: 'row', paddingHorizontal: 20, marginTop: 15, justifyContent: 'center', alignItems: 'center' },
    expressBadge: { backgroundColor: '#fff3e0', paddingHorizontal: 16, paddingVertical: 4, borderRadius: 16, marginRight: 10 },
    expressText: { color: COLORS.processScanOrange, fontWeight: 'bold', fontSize: 13 },
    statusBadge: { paddingHorizontal: 16, paddingVertical: 4, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)' },
    statusText: { color: '#FFF', fontWeight: 'bold', fontSize: 13 },
    customerBar: {
        backgroundColor: COLORS.white,
        marginHorizontal: 20,
        marginTop: -25,
        padding: 15,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#edf1ed',
        zIndex: 10,
    },
    customerHeader: { flexDirection: 'row', alignItems: 'center' },
    custName: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary, marginBottom: 2 },
    custPhone: { fontSize: 14, color: '#7b867e' },
    actionBtnCall: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
    },
    actionBtnMap: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#edf8ef',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
    },
    divider: { height: 1, backgroundColor: '#edf1ed', marginVertical: 12 },
    addressRow: { flexDirection: 'row', alignItems: 'flex-start' },
    addressText: { flex: 1, fontSize: 14, color: '#334155', lineHeight: 20 },
    scrollView: { flex: 1 },
    scrollContent: { padding: 15, paddingTop: 15, paddingBottom: 100 },
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 20,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#edf1ed',
    },
    infoGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
    codBox: {
        flex: 1,
        backgroundColor: '#fff3e0',
        borderRadius: 16,
        padding: 20,
        marginRight: 10,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#ffd59e',
    },
    codLabel: { fontSize: 11, fontWeight: 'bold', color: COLORS.processScanOrange, marginBottom: 8 },
    codValue: { fontSize: 24, fontWeight: 'bold', color: COLORS.processScanOrange },
    codUnit: { fontSize: 13, color: COLORS.processScanOrange, marginTop: 4 },
    rightStats: { flex: 1 },
    statBox: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 15,
        borderWidth: 1,
        borderColor: '#edf1ed',
    },
    statLabel: { fontSize: 11, fontWeight: 'bold', color: '#7b867e', marginBottom: 4 },
    statValue: { fontSize: 16, fontWeight: '600', color: COLORS.primary },
    statUnitInline: { fontSize: 13, color: '#7b867e', fontWeight: 'normal' },
    noteLabel: { fontSize: 13, fontWeight: 'bold', color: COLORS.primary, marginBottom: 8 },
    noteText: { fontSize: 15, color: COLORS.primary, lineHeight: 22 },
    timelineHeaderRow: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#edf1ed', paddingBottom: 15 },
    dotPrimaryTitle: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.secondary, marginRight: 8 },
    timelineTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.primary },
    trackItemContainer: { flexDirection: 'row' },
    timeline: { alignItems: 'center', width: 30 },
    timelineDotActiveWrap: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#edf8ef', justifyContent: 'center', alignItems: 'center', zIndex: 1 },
    timelineDotActive: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.secondary },
    timelineDotPast: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#FFF', borderWidth: 2, borderColor: COLORS.secondary, zIndex: 1, marginTop: 4 },
    timelineDotStart: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#FFF', borderWidth: 2, borderColor: '#D1D5DB', zIndex: 1, marginTop: 4 },
    timelineLine: { flex: 1, width: 2, backgroundColor: '#edf1ed', marginVertical: -4 },
    trackItem: { paddingLeft: 10, paddingBottom: 25, flex: 1 },
    trackStatus: { fontSize: 15, fontWeight: '500', color: COLORS.primary, marginBottom: 4 },
    trackTime: { fontSize: 13, color: '#7b867e' },
    emptyText: { textAlign: 'center', color: '#7b867e', fontStyle: 'italic', marginTop: 15 },
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        padding: 15,
        paddingBottom: 25,
        borderTopWidth: 1,
        borderTopColor: '#edf1ed',
    },
    printerBtn: {
        width: 56,
        height: 56,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
        borderWidth: 1,
        borderColor: '#edf1ed',
    },
    updateBtn: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    updateBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
});

export default TaskDetailStyles;
