import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const TaskListStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    headerArea: {
        backgroundColor: COLORS.headerBg,
        paddingHorizontal: 20,
        paddingTop: 50,
        paddingBottom: 50,
        position: 'relative',
        overflow: 'hidden',
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -30,
        right: -60,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    greeting: { color: 'rgba(255,255,255,0.8)', fontSize: 14, marginBottom: 4 },
    name: { color: COLORS.white, fontSize: 24, fontWeight: 'bold' },
    headerRight: { flexDirection: 'row', alignItems: 'center' },
    roleBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.15)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 10,
    },
    roleDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.secondary, marginRight: 6 },
    roleText: { color: COLORS.white, fontSize: 12, fontWeight: 'bold' },
    avatarWrap: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabContainerWrapper: { alignItems: 'center', marginTop: -25, zIndex: 10 },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: COLORS.white,
        padding: 5,
        borderRadius: 30,
        width: '90%',
        borderWidth: 1,
        borderColor: COLORS.borderLight,
    },
    tabButton: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 25 },
    tabButtonActive: { backgroundColor: COLORS.primary },
    tabText: { fontSize: 15, color: COLORS.textMuted, fontWeight: '600' },
    tabTextActive: { color: COLORS.white, fontWeight: 'bold' },
    warningBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.warningBg,
        padding: 14,
        borderRadius: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: COLORS.warning,
    },
    warningText: { color: COLORS.processScanOrange, fontSize: 14, marginLeft: 10, fontWeight: '500', flex: 1 },
    listContent: { padding: 15, paddingTop: 30, paddingBottom: 100 },
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: COLORS.borderLight,
    },
    cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
    codeWrap: { flex: 1, paddingRight: 10 },
    code: { fontSize: 17, fontWeight: 'bold', color: COLORS.primary, marginBottom: 4 },
    nameLine: { fontSize: 14, color: COLORS.textMain, fontWeight: '600' },
    phoneLine: { fontSize: 13, color: COLORS.textMuted, marginTop: 2 },
    statusBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 14 },
    statusText: { fontSize: 12, fontWeight: 'bold' },
    addressRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
    addressText: { flex: 1, fontSize: 14, color: COLORS.neutralMuted, lineHeight: 20 },
    metaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    serviceBadge: { backgroundColor: COLORS.backgroundSoft, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 },
    serviceBadgeText: { fontSize: 12, fontWeight: 'bold', color: COLORS.primary },
    codText: { fontSize: 13, color: COLORS.textMuted, fontWeight: '600' },
    emptyState: { alignItems: 'center', marginTop: 80 },
    emptyTitle: { fontSize: 22, fontWeight: 'bold', color: COLORS.primary, marginTop: 10 },
    emptySub: { fontSize: 15, color: COLORS.textMuted, marginTop: 5, textAlign: 'center' },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
});

export default TaskListStyles;
