import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from '../constants/theme';

const UpdateStatusStyles = StyleSheet.create({
  flex1: { flex: 1 },
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  headerArea: { backgroundColor: COLORS.headerBg, paddingTop: SPACING.lg, paddingBottom: SPACING.lg },
  headerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.md },
  backBtn: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.primaryLight, justifyContent: 'center', alignItems: 'center' },
  headerCenter: { alignItems: 'center' },
  headerSubTitle: { color: COLORS.greenSubtleText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  headerTitle: { color: COLORS.white, fontSize: TYPOGRAPHY.fontSize.subtitle, lineHeight: TYPOGRAPHY.lineHeight.subtitle, fontWeight: TYPOGRAPHY.fontWeight.bold },
  headerRightPlaceholder: { width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin },
  customerBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.cardBg, marginHorizontal: SPACING.md, marginTop: -SPACING.md, padding: SPACING.md, borderRadius: BORDER_RADIUS.lg, borderWidth: 1, borderColor: COLORS.borderLight, ...SHADOWS.sm },
  custName: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.body, lineHeight: TYPOGRAPHY.lineHeight.body, fontWeight: TYPOGRAPHY.fontWeight.bold, marginLeft: SPACING.sm, flex: 1 },
  custPhone: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.medium },
  codBadge: { backgroundColor: COLORS.warningBg, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.round },
  codBadgeText: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  scrollContent: { paddingHorizontal: SPACING.md, paddingTop: SPACING.md, paddingBottom: SPACING.xxl, gap: SPACING.md },
  statusToggleCard: { flexDirection: 'row', backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.xs, borderWidth: 1, borderColor: COLORS.borderLight, gap: SPACING.xs },
  toggleBtn: { flex: 1, minHeight: TOUCH_TARGET.androidMin, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.md },
  toggleBtnActiveSuccess: { backgroundColor: COLORS.secondary },
  toggleBtnActiveFail: { backgroundColor: COLORS.error },
  toggleText: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  toggleTextActive: { color: COLORS.white },
  card: { backgroundColor: COLORS.cardBg, borderRadius: BORDER_RADIUS.lg, padding: SPACING.md, gap: SPACING.sm, ...SHADOWS.sm },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
  dotWarning: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.warningText },
  cardTitleWarning: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  dotPrimary: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.secondary },
  cardTitlePrimary: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  dotDanger: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.error },
  cardTitleDanger: { color: COLORS.error, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  dotGray: { width: SPACING.sm, height: SPACING.sm, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.textMuted },
  cardTitleGray: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold, textTransform: 'uppercase' },
  expectedText: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  requiredBadge: { backgroundColor: COLORS.errorBg, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs, borderRadius: BORDER_RADIUS.round },
  requiredText: { color: COLORS.error, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.bold },
  codInputWrapper: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  codInput: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.headingLg, lineHeight: TYPOGRAPHY.lineHeight.headingLg, fontWeight: TYPOGRAPHY.fontWeight.bold, textAlign: 'center' },
  codCurrency: { color: COLORS.warningText, fontSize: TYPOGRAPHY.fontSize.headingSm, lineHeight: TYPOGRAPHY.lineHeight.headingSm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  quickActionRow: { flexDirection: 'row', gap: SPACING.sm },
  quickBtn: { flex: 1, minHeight: TOUCH_TARGET.androidMin, backgroundColor: COLORS.inputBg, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight },
  quickBtnActive: { backgroundColor: COLORS.warningBg, borderColor: COLORS.warningText },
  quickBtnText: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  quickBtnTextActive: { color: COLORS.warningText, fontWeight: TYPOGRAPHY.fontWeight.bold },
  cameraBox: { borderWidth: 1, borderColor: COLORS.primary, borderRadius: BORDER_RADIUS.md, minHeight: SPACING.xxl * 3, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.secondaryLight, gap: SPACING.xs },
  cameraBoxTitle: { color: COLORS.primary, fontSize: TYPOGRAPHY.fontSize.bodySm, lineHeight: TYPOGRAPHY.lineHeight.bodySm, fontWeight: TYPOGRAPHY.fontWeight.bold },
  cameraBoxSub: { color: COLORS.textMuted, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.medium },
  podImage: { width: '100%', height: SPACING.xxl * 5, borderRadius: BORDER_RADIUS.md, resizeMode: 'cover' },
  reCamBtn: { position: 'absolute', bottom: SPACING.sm, right: SPACING.sm, width: TOUCH_TARGET.androidMin, height: TOUCH_TARGET.androidMin, borderRadius: BORDER_RADIUS.round, backgroundColor: COLORS.inputWrapperBg, justifyContent: 'center', alignItems: 'center' },
  galleryBtn: { minHeight: TOUCH_TARGET.androidMin },
  inputNotePlain: { minHeight: SPACING.xxl + SPACING.lg, textAlignVertical: 'top' },
  inputNoteArea: { minHeight: SPACING.xxl + SPACING.xl, textAlignVertical: 'top' },
  footer: { backgroundColor: COLORS.white, borderTopWidth: 1, borderTopColor: COLORS.borderLight, paddingHorizontal: SPACING.md, paddingTop: SPACING.sm, gap: SPACING.sm },
  summaryBanner: { flexDirection: 'row', backgroundColor: COLORS.secondaryLight, padding: SPACING.sm, borderRadius: BORDER_RADIUS.md, justifyContent: 'space-between', alignItems: 'center' },
  summaryBannerText: { color: COLORS.secondary, fontSize: TYPOGRAPHY.fontSize.caption, lineHeight: TYPOGRAPHY.lineHeight.caption, fontWeight: TYPOGRAPHY.fontWeight.semibold },
  submitBtn: { minHeight: TOUCH_TARGET.androidMin },
});

export default UpdateStatusStyles;
