import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const UpdateStatusStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    headerArea: { backgroundColor: COLORS.headerBg, paddingTop: 50, paddingBottom: 30, position: 'relative', overflow: 'hidden' },
    headerCircleDecoration: { position: 'absolute', top: -50, right: -50, width: 250, height: 250, borderRadius: 125, backgroundColor: 'rgba(255,255,255,0.05)' },
    headerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15 },
    backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
    headerSubTitle: { color: 'rgba(255,255,255,0.7)', fontSize: 11, fontWeight: 'bold', letterSpacing: 1, marginBottom: 2 },
    headerTitle: { color: COLORS.white, fontSize: 20, fontWeight: 'bold' },
    customerBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        marginHorizontal: 20,
        marginTop: -20,
        padding: 15,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.borderLight,
        zIndex: 10,
    },
    custName: { fontSize: 15, fontWeight: 'bold', color: COLORS.primary, marginLeft: 10, flex: 1 },
    custPhone: { fontSize: 14, color: COLORS.textMuted, marginHorizontal: 10 },
    codBadge: { backgroundColor: COLORS.warningBg, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    codBadgeText: { color: COLORS.processScanOrange, fontSize: 12, fontWeight: 'bold' },
    scrollContent: { padding: 15, paddingTop: 25, paddingBottom: 150 },
    statusToggleCard: { flexDirection: 'row', backgroundColor: COLORS.white, borderRadius: 16, padding: 6, marginBottom: 15, borderWidth: 1, borderColor: COLORS.borderLight },
    toggleBtn: { flex: 1, flexDirection: 'row', paddingVertical: 14, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
    toggleBtnActiveSuccess: { backgroundColor: COLORS.secondary },
    toggleBtnActiveFail: { backgroundColor: COLORS.error },
    toggleText: { fontSize: 15, fontWeight: '600', color: COLORS.textMuted },
    card: { backgroundColor: COLORS.white, borderRadius: 16, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: COLORS.borderLight },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
    dotWarning: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.processScanOrange, marginRight: 8 },
    cardTitleWarning: { fontSize: 13, fontWeight: 'bold', color: COLORS.processScanOrange },
    dotPrimary: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.secondary, marginRight: 8 },
    cardTitlePrimary: { fontSize: 13, fontWeight: 'bold', color: COLORS.primary },
    dotDanger: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.error, marginRight: 8 },
    cardTitleDanger: { fontSize: 13, fontWeight: 'bold', color: COLORS.error },
    dotGray: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.textMuted, marginRight: 8 },
    cardTitleGray: { fontSize: 13, fontWeight: 'bold', color: COLORS.textMuted },
    expectedText: { fontSize: 13, color: COLORS.primary, fontWeight: '500' },
    requiredBadge: { backgroundColor: COLORS.errorBg, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 12 },
    requiredText: { color: COLORS.error, fontSize: 11, fontWeight: 'bold' },
    codInputWrapper: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
    codInput: { fontSize: 36, fontWeight: 'bold', color: COLORS.processScanOrange, textAlign: 'center', minWidth: 120 },
    codCurrency: { fontSize: 24, fontWeight: 'bold', color: COLORS.processScanOrange, marginLeft: 8, marginTop: 6 },
    quickActionRow: { flexDirection: 'row', justifyContent: 'space-between' },
    quickBtn: { flex: 1, backgroundColor: COLORS.inputBg, paddingVertical: 12, alignItems: 'center', borderRadius: 10, marginHorizontal: 4, borderWidth: 1, borderColor: 'transparent' },
    quickBtnActive: { backgroundColor: COLORS.warningBg, borderColor: COLORS.warning },
    quickBtnText: { fontSize: 14, color: COLORS.textMuted, fontWeight: '600' },
    quickBtnTextActive: { color: COLORS.processScanOrange, fontWeight: 'bold' },
    cameraBox: { borderWidth: 1, borderColor: COLORS.primary, borderStyle: 'dashed', borderRadius: 12, height: 160, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.secondaryLight, marginBottom: 15 },
    cameraBoxTitle: { color: COLORS.primary, fontSize: 15, fontWeight: 'bold', marginTop: 10, marginBottom: 4 },
    cameraBoxSub: { color: COLORS.textMuted, fontSize: 12 },
    podImage: { width: '100%', height: 250, borderRadius: 12, resizeMode: 'cover' },
    reCamBtn: { position: 'absolute', bottom: 15, right: 15, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
    galleryBtn: { flexDirection: 'row', backgroundColor: COLORS.inputBg, paddingVertical: 14, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
    galleryBtnText: { color: COLORS.primary, fontWeight: '600', fontSize: 15 },
    inputNotePlain: { fontSize: 15, color: COLORS.primary, lineHeight: 22, height: 80, textAlignVertical: 'top' },
    inputNoteArea: { backgroundColor: COLORS.inputBg, borderRadius: 12, padding: 15, fontSize: 15, color: COLORS.primary, height: 120, textAlignVertical: 'top' },
    footer: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 15, paddingBottom: 25, backgroundColor: COLORS.white, borderTopWidth: 1, borderColor: COLORS.borderLight },
    summaryBanner: { flexDirection: 'row', backgroundColor: COLORS.secondaryLight, padding: 12, borderRadius: 8, justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
    summaryBannerText: { color: COLORS.secondary, fontSize: 13, fontWeight: '600' },
    submitBtn: { flexDirection: 'row', paddingVertical: 16, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    submitText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
});

export default UpdateStatusStyles;
