import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";

const WarehouseDashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  headerArea: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 60 : 50,
    paddingBottom: 24,
    backgroundColor: COLORS.headerBg,
  },
  headerTitle: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
  },
  headerSubtitle: { color: COLORS.greenSubtleText, fontSize: 14 },
  loading: { marginTop: 60 },
  content: { paddingHorizontal: 20, paddingBottom: 40 },
  widgetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  widgetCard: {
    width: "48%",
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
  },
  widgetTitle: {
    fontSize: 13,
    color: COLORS.neutralMuted,
    marginBottom: 8,
  },
  widgetValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.neutralDark,
  },
  widgetLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginTop: 6,
  },
  widgetBadge: {
    marginTop: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  widgetBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.white,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
    marginTop: 15,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 16,
    marginRight: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  statLabel: { fontSize: 13, color: COLORS.neutralMuted, marginBottom: 8 },
  statValue: { fontSize: 22, fontWeight: "bold", color: COLORS.primary },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.primary,
    marginBottom: 12,
    marginTop: 4,
  },
  slaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  slaCard: {
    flex: 1,
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    padding: 14,
    marginRight: 10,
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
  },
  slaLabel: { fontSize: 12, color: COLORS.neutralMuted, marginBottom: 6 },
  slaValue: { fontSize: 20, fontWeight: "bold", color: COLORS.primary },
  actionCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 1,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  iconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: COLORS.greenSubtle,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  actionLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textMain,
  },
});

export default WarehouseDashboardStyles;
