import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../constants/colors';

const WarehouseMenuStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
    mainHeader: {
        backgroundColor: COLORS.headerBg,
        paddingTop: Platform.OS === 'ios' ? 60 : 50,
        paddingHorizontal: 20,
        paddingBottom: 40,
        position: 'relative',
        overflow: 'hidden',
    },
    headerCircleDecoration: {
        position: 'absolute',
        top: -50,
        right: -50,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 25,
    },
    hubInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.15)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    hubIconWrap: {
        backgroundColor: COLORS.white,
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    hubName: { color: COLORS.white, fontWeight: '600', fontSize: 14 },
    headerSubTitle: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 13,
        fontWeight: 'bold',
        letterSpacing: 1,
        marginBottom: 5,
    },
    headerTitle: { color: COLORS.white, fontSize: 32, fontWeight: '300', marginBottom: 25 },
    statsRow: { flexDirection: 'row', justifyContent: 'space-between' },
    statCard: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.15)',
        padding: 12,
        borderRadius: 12,
        marginHorizontal: 4,
    },
    statLabel: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: 'bold', marginBottom: 4 },
    statValue: { color: COLORS.white, fontSize: 22, fontWeight: 'bold' },
    statUnit: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginTop: 2 },

    scrollContent: { paddingBottom: 40 },
    sectionTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        color: COLORS.neutralMid,
        letterSpacing: 1,
        marginBottom: 15,
        paddingHorizontal: 16,
        paddingTop: 16,
    },

    // --- Main Cards ---
    mainCard: {
        width: '100%',
        backgroundColor: COLORS.cardBg,
        borderRadius: 20,
        padding: 16,
        marginBottom: 15,
        marginHorizontal: 16,
        minHeight: 120,
        elevation: 2,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
    },
    mainCardPrimary: { backgroundColor: COLORS.primary },
    mainCardIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    mainCardTextWrap: { flex: 1, justifyContent: 'flex-end' },
    mainCardTitle: { fontSize: 16, fontWeight: '600', color: COLORS.textMain, marginBottom: 4 },
    mainCardSub: { fontSize: 12, color: COLORS.neutralMuted },

    // --- List Items ---
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.neutralBorder,
    },
    listIconWrap: {
        width: 40,
        height: 40,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    listTextWrap: { flex: 1 },
    listTitle: { fontSize: 15, fontWeight: '600', color: COLORS.neutralDark, marginBottom: 4 },
    listSub: { fontSize: 13, color: COLORS.neutralMuted },
    badge: {
        backgroundColor: COLORS.amberAccentBg,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginRight: 10,
    },
    badgeText: { color: COLORS.amberAccentText, fontSize: 12, fontWeight: 'bold' },
});

export default WarehouseMenuStyles;
