import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

const WaybillListStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundSoft },
  headerArea: {
    backgroundColor: COLORS.headerBg,
    paddingTop: 50,
    paddingBottom: 30,
    paddingHorizontal: 15,
    position: "relative",
    overflow: "hidden",
  },
  headerCircleDecoration: {
    position: "absolute",
    top: -30,
    right: -60,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  exportBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: { color: COLORS.white, fontSize: 18, fontWeight: "bold" },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 16,
    height: 56,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 15,
    color: COLORS.primary,
  },
  scanBtn: { padding: 10 },
  searchDivider: { width: 1, height: 25, backgroundColor: COLORS.borderLight },
  filterBtn: { padding: 10, paddingRight: 15 },
  listContent: { padding: 15, paddingBottom: 100 },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    overflow: "hidden",
  },
  cardExpress: { borderColor: COLORS.processScanOrange },
  expressBanner: {
    backgroundColor: COLORS.warningBg,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  expressBannerText: {
    color: COLORS.processScanOrange,
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  cardInner: { padding: 16 },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingRight: 40,
  },
  waybillCode: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
    marginTop: 8,
  },
  slaBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    backgroundColor: COLORS.successBg,
  },
  slaBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.successAccent,
  },
  overdueCard: { backgroundColor: COLORS.OVERDUE_BG },
  typeBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  typeBadgeNormal: { backgroundColor: COLORS.backgroundSoft },
  typeBadgeExpress: { backgroundColor: COLORS.warningBg },
  typeText: { fontSize: 11, fontWeight: "bold", letterSpacing: 0.5 },
  typeTextNormal: { color: COLORS.textMuted },
  typeTextExpress: { color: COLORS.processScanOrange },
  custInfo: {
    fontSize: 14,
    color: COLORS.primary,
    marginBottom: 8,
    fontWeight: "500",
  },
  addressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 15,
    paddingRight: 10,
  },
  addressText: {
    fontSize: 14,
    color: COLORS.textMuted,
    lineHeight: 20,
    flex: 1,
  },
  divider: { height: 1, backgroundColor: COLORS.borderLight, marginBottom: 15 },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerLabel: { fontSize: 13, color: COLORS.textMuted, fontWeight: "500" },
  footerCodValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.processScanOrange,
  },
  footerNoCod: { fontSize: 16, fontWeight: "bold", color: COLORS.primary },
  actionMenuBtn: { position: "absolute", top: 15, right: 10, zIndex: 10 },
  actionMenuBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.background,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  emptyState: { alignItems: "center", marginTop: 80 },
  emptyStateText: {
    color: COLORS.textMuted,
    marginTop: 10,
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
  },
  fab: {
    position: "absolute",
    bottom: 30,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 25,
    paddingBottom: 40,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
  },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.primary },
  label: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 10,
  },
  filterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  dateChip: {
    flex: 1,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 5,
    backgroundColor: COLORS.backgroundSoft,
  },
  dateChipActive: {
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.secondary,
  },
  dateChipText: { color: COLORS.primary, fontWeight: "500" },
  dateChipTextActive: { color: COLORS.white, fontWeight: "bold" },
  submitBtn: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  btnText: { color: COLORS.white, fontWeight: "bold", fontSize: 16 },
  actionSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 25,
    paddingBottom: 40,
  },
  actionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 20,
    textAlign: "center",
  },
  actionBtnRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
  },
  actionIconBg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  actionBtnText: { fontSize: 16, fontWeight: "600", color: COLORS.primary },
  dividerAction: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginVertical: 10,
  },
  detailBox: {
    backgroundColor: COLORS.backgroundSoft,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  detailRow: { marginBottom: 10 },
  detailLabel: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "bold",
    marginBottom: 2,
  },
  detailValue: { fontSize: 14, color: COLORS.primary },
  weightInput: {
    borderWidth: 2,
    borderColor: COLORS.secondary,
    borderRadius: 16,
    padding: 20,
    fontSize: 32,
    textAlign: "center",
    fontWeight: "bold",
    color: COLORS.secondary,
    marginBottom: 10,
    backgroundColor: COLORS.secondaryLight,
  },
  cancelBtn: {
    flex: 1,
    padding: 16,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    marginRight: 8,
    backgroundColor: COLORS.backgroundSoft,
  },
  saveBtn: {
    flex: 1,
    padding: 16,
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: COLORS.secondary,
    marginLeft: 8,
  },
});

export default WaybillListStyles;
