"""verified_sync

Revision ID: 3f00305f7ff3
Revises: 
Create Date: 2026-04-05 23:18:04.173098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f00305f7ff3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.alter_column('pricing_rules', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pricing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint('unique_pricing_rule', 'pricing_rules', ['policy_id', 'from_province_id', 'to_province_id', 'service_type', 'min_weight', 'max_weight'])
    op.alter_column('statement_cod', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statement_cod', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('statement_cod', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('statement_cod', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('statement_cod', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'statement_cod', 'users', ['created_by'], ['user_id'])
    op.alter_column('statement_details', 'ledger_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('transaction_ledger', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('transaction_ledger', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transaction_ledger', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_transaction_ledger_parent_transaction_id'), 'transaction_ledger', ['parent_transaction_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('waybills', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waybills', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_transaction_ledger_parent_transaction_id'), table_name='transaction_ledger')
    op.alter_column('transaction_ledger', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('transaction_ledger', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transaction_ledger', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('statement_details', 'ledger_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'statement_cod', type_='foreignkey')
    op.alter_column('statement_cod', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statement_cod', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('statement_cod', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('statement_cod', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('statement_cod', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_pricing_rule', 'pricing_rules', type_='unique')
    op.alter_column('pricing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('pricing_rules', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
