"""add_zones_and_adjustments

Revision ID: 06036a9f182e
Revises: b9b4b6d5e2f2
Create Date: 2026-05-11 21:19:18.905770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06036a9f182e'
down_revision: Union[str, Sequence[str], None] = 'b9b4b6d5e2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
