"""add_remote_areas_and_accounting

Revision ID: 3157d0cd1c94
Revises: a63ba99967bd
Create Date: 2026-05-11 15:16:30.272769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3157d0cd1c94'
down_revision: Union[str, Sequence[str], None] = 'a63ba99967bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_hubs_manager', 'hubs', 'users', ['manager_id'], ['user_id'])
    op.add_column('statement_debt', sa.Column('status', sa.String(length=50), server_default=sa.text("'DRAFT'"), nullable=False))
    op.add_column('statement_debt', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('statement_debt', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statement_debt', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statement_debt', type_='foreignkey')
    op.drop_column('statement_debt', 'created_by')
    op.drop_column('statement_debt', 'created_at')
    op.drop_column('statement_debt', 'status')
    op.drop_constraint('fk_hubs_manager', 'hubs', type_='foreignkey')
    # ### end Alembic commands ###
