"""add_latitude_and_longitude_to_hubs

Revision ID: 4f1bced602f5
Revises: accf93260ee7
Create Date: 2026-07-08 23:07:07.939680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1bced602f5'
down_revision: Union[str, Sequence[str], None] = 'accf93260ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bags', 'actual_quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bags', 'materialization_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_constraint(op.f('bags_booking_request_id_fkey'), 'bags', type_='foreignkey')
    op.create_foreign_key('bags_booking_request_id_fkey', 'bags', 'booking_requests', ['booking_request_id'], ['request_id'])
    op.alter_column('booking_requests', 'pickup_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'SINGLE_WAYBILL'::character varying"))
    op.alter_column('booking_requests', 'actual_quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('booking_requests', 'materialization_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'NOT_REQUIRED'::character varying"))
    op.drop_constraint(op.f('bulk_mail_draft_items_bag_id_fkey'), 'bulk_mail_draft_items', type_='foreignkey')
    op.drop_constraint(op.f('bulk_mail_draft_items_request_id_fkey'), 'bulk_mail_draft_items', type_='foreignkey')
    op.drop_constraint(op.f('bulk_mail_draft_items_waybill_id_fkey'), 'bulk_mail_draft_items', type_='foreignkey')
    op.create_foreign_key('bulk_mail_draft_items_bag_id_fkey', 'bulk_mail_draft_items', 'bags', ['bag_id'], ['bag_id'])
    op.create_foreign_key('bulk_mail_draft_items_request_id_fkey', 'bulk_mail_draft_items', 'booking_requests', ['request_id'], ['request_id'])
    op.create_foreign_key('bulk_mail_draft_items_waybill_id_fkey', 'bulk_mail_draft_items', 'waybills', ['waybill_id'], ['waybill_id'])
    op.alter_column('customer_departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('hubs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hubs', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('packing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('waybills', 'price_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('price_status', sa.VARCHAR(length=30), server_default=sa.text("'ESTIMATED'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('packing_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('hubs', 'longitude')
    op.drop_column('hubs', 'latitude')
    op.alter_column('customer_departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('bulk_mail_draft_items_waybill_id_fkey', 'bulk_mail_draft_items', type_='foreignkey')
    op.drop_constraint('bulk_mail_draft_items_request_id_fkey', 'bulk_mail_draft_items', type_='foreignkey')
    op.drop_constraint('bulk_mail_draft_items_bag_id_fkey', 'bulk_mail_draft_items', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_mail_draft_items_waybill_id_fkey'), 'bulk_mail_draft_items', 'waybills', ['waybill_id'], ['waybill_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bulk_mail_draft_items_request_id_fkey'), 'bulk_mail_draft_items', 'booking_requests', ['request_id'], ['request_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bulk_mail_draft_items_bag_id_fkey'), 'bulk_mail_draft_items', 'bags', ['bag_id'], ['bag_id'], ondelete='CASCADE')
    op.alter_column('booking_requests', 'materialization_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'NOT_REQUIRED'::character varying"))
    op.alter_column('booking_requests', 'actual_quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('booking_requests', 'pickup_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'SINGLE_WAYBILL'::character varying"))
    op.drop_constraint('bags_booking_request_id_fkey', 'bags', type_='foreignkey')
    op.create_foreign_key(op.f('bags_booking_request_id_fkey'), 'bags', 'booking_requests', ['booking_request_id'], ['request_id'], ondelete='SET NULL')
    op.alter_column('bags', 'materialization_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('bags', 'actual_quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
