"""add_zone_name_to_pricing_rules

Revision ID: 5fe7766fb92b
Revises: 06036a9f182e
Create Date: 2026-05-11 21:21:03.707684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe7766fb92b'
down_revision: Union[str, Sequence[str], None] = '06036a9f182e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('zone_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'zone_name')
    # ### end Alembic commands ###
