"""add_verify_fields

Revision ID: a63ba99967bd
Revises: f8458ba16c31
Create Date: 2026-05-11 12:38:13.422374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63ba99967bd'
down_revision: Union[str, Sequence[str], None] = 'f8458ba16c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_hubs_manager', 'hubs', 'users', ['manager_id'], ['user_id'])
    op.add_column('waybills', sa.Column('bill_image_url', sa.String(length=255), nullable=True))
    op.add_column('waybills', sa.Column('pickup_image_url', sa.String(length=255), nullable=True))
    op.add_column('waybills', sa.Column('ocr_status', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True))
    op.add_column('waybills', sa.Column('verify_status', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True))
    op.add_column('waybills', sa.Column('verify_error_msg', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybills', 'verify_error_msg')
    op.drop_column('waybills', 'verify_status')
    op.drop_column('waybills', 'ocr_status')
    op.drop_column('waybills', 'pickup_image_url')
    op.drop_column('waybills', 'bill_image_url')
    op.drop_constraint('fk_hubs_manager', 'hubs', type_='foreignkey')
    # ### end Alembic commands ###
