"""add_pickup_request_and_bag_fields

Revision ID: a8bde70b092d
Revises: f8458ba16c32
Create Date: 2026-05-20 13:36:42.409848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bde70b092d'
down_revision: Union[str, Sequence[str], None] = 'f8458ba16c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('bag_type', sa.String(length=20), server_default=sa.text("'EXPORT'"), nullable=True))
    op.add_column('bags', sa.Column('est_quantity', sa.Integer(), nullable=True))
    op.add_column('bags', sa.Column('pickup_time', sa.DateTime(), nullable=True))
    op.add_column('booking_requests', sa.Column('est_quantity', sa.Integer(), nullable=True))
    op.add_column('booking_requests', sa.Column('priority', sa.String(length=20), server_default=sa.text("'NORMAL'"), nullable=True))
    op.add_column('booking_requests', sa.Column('sla_deadline', sa.DateTime(), nullable=True))
    op.add_column('booking_requests', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('waybills', 'dest_ward_id')
    op.drop_column('waybills', 'dest_district_id')
    op.drop_column('waybills', 'sender_ward_id')
    op.drop_column('waybills', 'volumetric_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybills', sa.Column('volumetric_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('waybills', sa.Column('sender_ward_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('waybills', sa.Column('dest_district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('waybills', sa.Column('dest_ward_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking_requests', 'notes')
    op.drop_column('booking_requests', 'sla_deadline')
    op.drop_column('booking_requests', 'priority')
    op.drop_column('booking_requests', 'est_quantity')
    op.drop_column('bags', 'pickup_time')
    op.drop_column('bags', 'est_quantity')
    op.drop_column('bags', 'bag_type')
    # ### end Alembic commands ###
