import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";
import {
  BORDER_RADIUS,
  SHADOWS,
  SPACING,
  TOUCH_TARGET,
  TYPOGRAPHY,
} from "../constants/theme";

export const FRAME_W = "90%";
export const FRAME_H = "65%";

export const getBottomTabsContainerStyle = (insets = { bottom: 0 }) => ({
  paddingBottom: Math.max(insets.bottom + SPACING.sm, SPACING.md),
});

const HomeStyles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    backgroundColor: COLORS.backgroundSoft,
  },

  headerBanner: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    paddingTop: Platform.OS === "ios" ? SPACING.sm : SPACING.lg,
    paddingBottom: SPACING.xl,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  homeTextGroup: {
    flex: 1,
    paddingRight: SPACING.sm,
  },
  homeGreeting: {
    color: COLORS.appTaglineColor,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: SPACING.xs,
  },
  homeName: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.headingSm,
    lineHeight: TYPOGRAPHY.lineHeight.headingSm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    letterSpacing: -0.3,
  },
  rolePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: SPACING.xs,
    marginTop: SPACING.sm,
    backgroundColor: COLORS.overlayWhite12,
    borderWidth: 1,
    borderColor: COLORS.overlayWhite18,
    borderRadius: BORDER_RADIUS.round,
    paddingHorizontal: SPACING.md_sm,
    paddingVertical: SPACING.xs,
  },
  roleDot: {
    width: SPACING.xs ,
    height: SPACING.xs ,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.secondary,
  },
  roleText: {
    color: COLORS.secondaryLight,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    letterSpacing: 0.2,
  },
  profileButton: {
    alignItems: "center",
    gap: SPACING.xs,
    justifyContent: "center",
  },
  avatarCircle: {
    width: SPACING.xxxl,
    height: SPACING.xxxl,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.secondaryLight,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  profileButtonText: {
    color: COLORS.appTaglineColor,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    letterSpacing: 0.3,
  },

  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md_sm,
    paddingHorizontal: SPACING.md,
    marginTop: -SPACING.lg,
    marginBottom: SPACING.sm,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.lg,
    paddingVertical: SPACING.md_sm,
    paddingHorizontal: SPACING.md_sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    ...SHADOWS.md,
  },
  statValue: {
    fontSize: TYPOGRAPHY.fontSize.subtitle,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    letterSpacing: -0.5,
  },
  statLabel: {
    color: COLORS.textGray,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    marginTop: SPACING.xxs,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  homeContent: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.xxl + SPACING.xl + SPACING.md,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: SPACING.lg,
    marginBottom: SPACING.md_sm,
  },
  sectionTitle: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    letterSpacing: 0.1,
  },
  sectionSub: {
    color: COLORS.textGray,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.regular,
  },

  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: SPACING.md_sm,
  },
  actionCard: {
    width: "48.5%",
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    overflow: "hidden",
    ...SHADOWS.sm,
  },
  cardTopAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: SPACING.xs ,
    borderTopLeftRadius: BORDER_RADIUS.xl,
    borderTopRightRadius: BORDER_RADIUS.xl,
  },
  actionIcon: {
    width: TOUCH_TARGET.androidMin - SPACING.xs ,
    height: TOUCH_TARGET.androidMin - SPACING.xs ,
    borderRadius: BORDER_RADIUS.lg,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: SPACING.md_sm,
    marginTop: SPACING.sm ,
  },
  actionLabel: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  actionSub: {
    color: COLORS.textGray,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.regular,
    marginTop: SPACING.xs ,
  },

  activityCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    overflow: "hidden",
    ...SHADOWS.sm,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md_sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md_sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  actDot: {
    width: SPACING.sm,
    height: SPACING.sm,
    borderRadius: BORDER_RADIUS.round,
    flexShrink: 0,
  },
  actTitle: {
    flex: 1,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.neutralDark,
  },
  actBadge: {
    paddingHorizontal: SPACING.sm ,
    paddingVertical: SPACING.xs ,
    borderRadius: BORDER_RADIUS.md,
  },
  actBadgeText: {
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  badgeGreen: {
    backgroundColor: COLORS.successBg,
    textColor: COLORS.successAccent,
  },
  badgeAmber: {
    backgroundColor: COLORS.amberAccentBg,
    textColor: COLORS.amberAccentText,
  },
  badgeBlue: {
    backgroundColor: COLORS.blueAccentBg,
    textColor: COLORS.blueAccent,
  },

  emptyState: {
    paddingVertical: SPACING.xl + SPACING.xs,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    gap: SPACING.md_sm,
  },
  emptyTitle: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  emptyText: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    textAlign: "center",
  },

  customizeActionText: {
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  viewMoreButton: {
    alignSelf: "flex-start",
    marginTop: SPACING.md_sm,
    minHeight: TOUCH_TARGET.androidMin,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md_sm,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.secondaryLight,
    justifyContent: "center",
  },
  viewMoreText: {
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  loadingActivity: {
    paddingVertical: SPACING.lg,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlayDark45,
    justifyContent: "center",
    paddingHorizontal: SPACING.lg - SPACING.xs,
    paddingVertical: SPACING.xl,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg - SPACING.xs,
    maxHeight: "86%",
  },
  modalTitle: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    marginBottom: SPACING.xs ,
  },
  modalSubtitle: {
    color: COLORS.textGray,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    marginBottom: SPACING.md_sm ,
  },
  modalList: {
    marginBottom: SPACING.md_sm,
  },
  modalListContent: {
    paddingBottom: SPACING.md_sm,
  },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACING.md_sm,
    paddingHorizontal: SPACING.md_sm,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.backgroundSoft,
    marginBottom: SPACING.md_sm,
  },
  modalItemText: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    flex: 1,
    marginRight: SPACING.md_sm,
  },
  modalItemAction: {
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  modalRemoveText: {
    color: COLORS.dangerAccent,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  modalSection: {
    marginTop: SPACING.md,
  },
  modalSectionTitle: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    marginBottom: SPACING.md_sm,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: SPACING.sm,
  },
  modalCancelButton: {
    minHeight: TOUCH_TARGET.androidMin,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md_sm,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.borderLight,
    justifyContent: "center",
  },
  modalCancelText: {
    color: COLORS.neutralDark,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },

  floatingAction: {
    position: "absolute",
    right: SPACING.lg - SPACING.xs,
    bottom: Platform.OS === "ios" ? SPACING.xxl + SPACING.xl + SPACING.sm : SPACING.xxl + SPACING.xl,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.round,
    minHeight: TOUCH_TARGET.androidMin,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md_sm,
    shadowColor: COLORS.primary,
    shadowOffset: { width: SPACING.hairline - SPACING.hairline, height: SPACING.xs },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 10,
  },
  floatingText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },

  bottomTabsContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: SPACING.sm,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    ...SHADOWS.md,
  },
  bottomTabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.xs ,
  },
  bottomTabIcon: {
    width: TOUCH_TARGET.androidMin - SPACING.xs ,
    height: TOUCH_TARGET.androidMin - SPACING.xs ,
    borderRadius: BORDER_RADIUS.lg,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: SPACING.xs ,
  },
  bottomTabIconActive: {
    backgroundColor: COLORS.greenSubtle,
  },
  bottomTabLabel: {
    color: COLORS.textGray,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    textAlign: "center",
  },
  bottomTabActive: {
    color: COLORS.secondary,
  },

  container: { flex: 1, backgroundColor: COLORS.neutralDark },

  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.formSectionBg,
    paddingHorizontal: SPACING.xl,
  },
  permissionIconWrap: {
    width: SPACING.xxl + SPACING.xl + SPACING.sm ,
    height: SPACING.xxl + SPACING.xl + SPACING.sm ,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.primaryLight,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.secondary,
  },
  permissionTitle: {
    fontSize: TYPOGRAPHY.fontSize.headingSm ,
    lineHeight: TYPOGRAPHY.lineHeight.headingSm ,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.white,
    marginBottom: SPACING.md_sm,
  },
  permissionDesc: {
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body ,
    color: COLORS.textGray,
    textAlign: "center",
    marginBottom: SPACING.xl,
  },
  btnPermission: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: TOUCH_TARGET.androidMin,
    backgroundColor: COLORS.secondary,
    paddingHorizontal: SPACING.xl - SPACING.xs,
    paddingVertical: SPACING.md,
    borderRadius: BORDER_RADIUS.round,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: SPACING.hairline - SPACING.hairline, height: SPACING.xs },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  btnPermissionText: {
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
  },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  maskContainer: { ...StyleSheet.absoluteFillObject },
  maskTop: { flex: 1, width: "100%", backgroundColor: COLORS.overlayDark65 },
  maskBottom: { flex: 1, width: "100%", backgroundColor: COLORS.overlayDark65 },
  maskCenter: { flexDirection: "row", height: FRAME_H },
  maskSide: { flex: 1, backgroundColor: COLORS.overlayDark65 },

  scanFrame: {
    width: FRAME_W,
    height: FRAME_H,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  scanHint: {
    color: COLORS.overlayWhite80,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    backgroundColor: COLORS.overlayDark50,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.round,
    overflow: "hidden",
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingTop: Platform.OS === "ios" ? SPACING.xxl + SPACING.sm  : SPACING.xxl - 3,
    paddingBottom: SPACING.md ,
    zIndex: 100,
  },
  headerBtn: {
    width: SPACING.xxxl,
    height: SPACING.xxxl,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.overlayBlack40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.overlayWhite10,
  },
  headerCenter: { flexDirection: "column", alignItems: "center" },
  headerTitle: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    color: COLORS.secondary,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    marginTop: SPACING.xxs,
  },
  queueBtn: {
    width: SPACING.xxxl,
    height: SPACING.xxxl,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.overlayBlack40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.overlayWhite10,
  },
  badge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: COLORS.error,
    borderRadius: BORDER_RADIUS.round,
    minWidth: SPACING.md + SPACING.xs,
    height: SPACING.md + SPACING.xs,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SPACING.xs,
    borderWidth: 1.5,
    borderColor: COLORS.neutralDark,
  },
  badgeText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },

  corner: { position: "absolute", width: SPACING.xxl - SPACING.sm, height: SPACING.xxl - SPACING.sm, zIndex: 30 },
  cornerHorizontal: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SPACING.xxl - SPACING.sm,
    height: SPACING.xs,
    backgroundColor: COLORS.secondary,
    borderRadius: BORDER_RADIUS.sm,
  },
  cornerVertical: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SPACING.xs,
    height: SPACING.xxl - SPACING.sm,
    backgroundColor: COLORS.secondary,
    borderRadius: BORDER_RADIUS.sm,
  },

  bottomBar: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: Platform.OS === "ios" ? SPACING.xxl - SPACING.xs  : SPACING.xl - SPACING.xs,
    paddingTop: SPACING.lg - SPACING.xs,
    alignItems: "center",
    backgroundColor: COLORS.neutralDark,
    zIndex: 100,
    borderTopWidth: 1,
    borderTopColor: COLORS.overlayWhite05,
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: SPACING.md_sm,
    marginBottom: SPACING.lg - SPACING.xs,
  },
  statChip: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: BORDER_RADIUS.round,
    paddingHorizontal: SPACING.md_sm,
    paddingVertical: SPACING.xs ,
  },
  statText: {
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },

  shutterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: SPACING.sm ,
  },
  sideBtn: {
    minWidth: TOUCH_TARGET.androidMin,
    minHeight: TOUCH_TARGET.androidMin,
    width: SPACING.xxl + SPACING.md ,
    height: SPACING.xxl + SPACING.md ,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.overlayWhite10,
    alignItems: "center",
    justifyContent: "center",
  },
  sideBtnLabel: {
    color: COLORS.overlayWhite90,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    marginTop: SPACING.xs,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  shutterOuter: {
    width: SPACING.xxl + SPACING.xxl - SPACING.md,
    height: SPACING.xxl + SPACING.xxl - SPACING.md,
    borderRadius: BORDER_RADIUS.round,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: SPACING.xs,
    borderColor: COLORS.white,
  },
  shutterInner: {
    width: SPACING.xxl + SPACING.md,
    height: SPACING.xxl + SPACING.md,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
  },
  versionText: {
    color: COLORS.overlayWhite20,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    marginTop: SPACING.md ,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },

  toastLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
  },
  menuSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.headerBg,
    borderTopLeftRadius: BORDER_RADIUS.xl + BORDER_RADIUS.lg,
    borderTopRightRadius: BORDER_RADIUS.xl + BORDER_RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    paddingBottom: Platform.OS === "ios" ? SPACING.xl + SPACING.sm : SPACING.lg,
    paddingTop: SPACING.md_sm,
    maxHeight: "85%",
    shadowColor: COLORS.textMain,
    shadowOffset: { width: SPACING.hairline - SPACING.hairline, height: -SPACING.md_sm },
    shadowOpacity: 0.3,
    elevation: 20,
  },
  sheetHandle: {
    width: SPACING.xxl - SPACING.sm,
    height: SPACING.xs ,
    backgroundColor: COLORS.overlayWhite20,
    borderRadius: BORDER_RADIUS.sm ,
    alignSelf: "center",
    marginBottom: SPACING.lg - SPACING.xs,
  },
  menuUserRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.lg - SPACING.xs,
    backgroundColor: COLORS.overlayWhite05,
    padding: SPACING.md_sm,
    borderRadius: BORDER_RADIUS.xl,
  },
  menuAvatar: {
    width: SPACING.xl + SPACING.md ,
    height: SPACING.xl + SPACING.md ,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.md_sm,
  },
  menuAvatarText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.subtitle ,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle ,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  menuUserName: {
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.white,
  },
  menuUserRole: {
    fontSize: TYPOGRAPHY.fontSize.bodySm ,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    color: COLORS.textGray,
    marginTop: SPACING.xs,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  closeSheetBtn: {
    width: SPACING.xxxl,
    height: SPACING.xxxl,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.overlayWhite10,
    justifyContent: "center",
    alignItems: "center",
  },
  sheetDivider: {
    height: SPACING.hairline,
    backgroundColor: COLORS.overlayWhite05,
    marginVertical: SPACING.md_sm,
  },
  sheetSectionLabel: {
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textGray,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
    marginLeft: SPACING.xs,
  },
  sheetItem: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: TOUCH_TARGET.androidMin,
    paddingVertical: SPACING.md_sm ,
    paddingHorizontal: SPACING.xs,
  },
  sheetIconBox: {
    width: TOUCH_TARGET.androidMin - SPACING.sm,
    height: TOUCH_TARGET.androidMin - SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.md,
  },
  sheetItemText: {
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.white,
    flex: 1,
  },
});

export default HomeStyles;


