import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";
import { BORDER_RADIUS, SHADOWS, SPACING, TOUCH_TARGET, TYPOGRAPHY } from "../constants/theme";

const ProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backgroundSoft,
  },
  header: {
    backgroundColor: COLORS.headerBg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.xl,
    alignItems: "center",
  },
  headerTitle: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.subtitle,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  scrollView: {
    flex: 1,
    marginTop: -SPACING.lg,
  },
  scrollContent: {
    paddingHorizontal: SPACING.md,
    paddingBottom: SPACING.xxl,
    gap: SPACING.md,
  },
  profileCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg,
    alignItems: "center",
    ...SHADOWS.md,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: SPACING.md,
  },
  avatarPlaceholder: {
    width: SPACING.xxl + SPACING.xxl,
    height: SPACING.xxl + SPACING.xxl,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.backgroundSoft,
    borderWidth: 2,
    borderColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: COLORS.primary,
    fontSize: TYPOGRAPHY.fontSize.heading,
    lineHeight: TYPOGRAPHY.lineHeight.heading,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  editBadge: {
    position: "absolute",
    right: SPACING.xs,
    bottom: SPACING.xs,
    minWidth: TOUCH_TARGET.iosMin,
    minHeight: TOUCH_TARGET.iosMin,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.white,
  },
  nameText: {
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.headingSm,
    lineHeight: TYPOGRAPHY.lineHeight.headingSm,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    textAlign: "center",
  },
  roleText: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  statusBadge: {
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    backgroundColor: COLORS.successBg,
    borderRadius: BORDER_RADIUS.round,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  statusDot: {
    width: SPACING.sm,
    height: SPACING.sm,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.successAccent,
  },
  statusText: {
    color: COLORS.successAccent,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  menuCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
    ...SHADOWS.sm,
  },
  menuItem: {
    minHeight: TOUCH_TARGET.androidMin,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
    paddingVertical: SPACING.sm,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  iconWrap: {
    width: TOUCH_TARGET.androidMin,
    height: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.backgroundSoft,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.sm,
  },
  menuLabelWrap: {
    flex: 1,
  },
  infoLabel: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  infoValue: {
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  codCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
    ...SHADOWS.sm,
  },
  codHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  codHeadLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  codIconWrap: {
    width: TOUCH_TARGET.androidMin,
    height: TOUCH_TARGET.androidMin,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.warningBg,
    justifyContent: "center",
    alignItems: "center",
  },
  codTitle: {
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.body,
    lineHeight: TYPOGRAPHY.lineHeight.body,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  codContent: {
    backgroundColor: COLORS.backgroundSoft,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    alignItems: "center",
  },
  codAmount: {
    color: COLORS.error,
    fontSize: TYPOGRAPHY.fontSize.heading,
    lineHeight: TYPOGRAPHY.lineHeight.heading,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
  codDesc: {
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    textAlign: "center",
  },
  logoutWrap: {
    marginTop: SPACING.sm,
  },
  logoutButton: {
    minHeight: TOUCH_TARGET.androidMin,
    borderColor: COLORS.error,
  },
  versionText: {
    textAlign: "center",
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.caption,
    lineHeight: TYPOGRAPHY.lineHeight.caption,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    marginTop: SPACING.sm,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.inputWrapperBg,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
  },
  modalContent: {
    width: "100%",
    backgroundColor: COLORS.cardBg,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg,
    alignItems: "center",
    ...SHADOWS.md,
  },
  modalWarningIcon: {
    width: SPACING.xxl,
    height: SPACING.xxl,
    borderRadius: BORDER_RADIUS.round,
    backgroundColor: COLORS.errorBg,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: SPACING.sm,
  },
  modalTitle: {
    color: COLORS.textMain,
    fontSize: TYPOGRAPHY.fontSize.subtitle,
    lineHeight: TYPOGRAPHY.lineHeight.subtitle,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    marginBottom: SPACING.xs,
  },
  modalDesc: {
    textAlign: "center",
    color: COLORS.textMuted,
    fontSize: TYPOGRAPHY.fontSize.bodySm,
    lineHeight: TYPOGRAPHY.lineHeight.bodySm,
    fontWeight: TYPOGRAPHY.fontWeight.regular,
    marginBottom: SPACING.md,
  },
  modalActions: {
    width: "100%",
    flexDirection: "row",
    gap: SPACING.sm,
  },
  modalAction: {
    flex: 1,
  },
});

export default ProfileStyles;
